// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: contentiontest.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentionTest0_TestContention0_FullMethodName = "/protobufs.ContentionTest0/TestContention0"
	ContentionTest0_Control_FullMethodName         = "/protobufs.ContentionTest0/Control"
)

// ContentionTest0Client is the client API for ContentionTest0 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentionTest0Client interface {
	TestContention0(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientRequest, ClientResponse], error)
	Control(ctx context.Context, in *ControlCommand, opts ...grpc.CallOption) (*ControlResponse, error)
}

type contentionTest0Client struct {
	cc grpc.ClientConnInterface
}

func NewContentionTest0Client(cc grpc.ClientConnInterface) ContentionTest0Client {
	return &contentionTest0Client{cc}
}

func (c *contentionTest0Client) TestContention0(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientRequest, ClientResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContentionTest0_ServiceDesc.Streams[0], ContentionTest0_TestContention0_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientRequest, ClientResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContentionTest0_TestContention0Client = grpc.BidiStreamingClient[ClientRequest, ClientResponse]

func (c *contentionTest0Client) Control(ctx context.Context, in *ControlCommand, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, ContentionTest0_Control_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentionTest0Server is the server API for ContentionTest0 service.
// All implementations must embed UnimplementedContentionTest0Server
// for forward compatibility.
type ContentionTest0Server interface {
	TestContention0(grpc.BidiStreamingServer[ClientRequest, ClientResponse]) error
	Control(context.Context, *ControlCommand) (*ControlResponse, error)
	mustEmbedUnimplementedContentionTest0Server()
}

// UnimplementedContentionTest0Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentionTest0Server struct{}

func (UnimplementedContentionTest0Server) TestContention0(grpc.BidiStreamingServer[ClientRequest, ClientResponse]) error {
	return status.Errorf(codes.Unimplemented, "method TestContention0 not implemented")
}
func (UnimplementedContentionTest0Server) Control(context.Context, *ControlCommand) (*ControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedContentionTest0Server) mustEmbedUnimplementedContentionTest0Server() {}
func (UnimplementedContentionTest0Server) testEmbeddedByValue()                         {}

// UnsafeContentionTest0Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentionTest0Server will
// result in compilation errors.
type UnsafeContentionTest0Server interface {
	mustEmbedUnimplementedContentionTest0Server()
}

func RegisterContentionTest0Server(s grpc.ServiceRegistrar, srv ContentionTest0Server) {
	// If the following call pancis, it indicates UnimplementedContentionTest0Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentionTest0_ServiceDesc, srv)
}

func _ContentionTest0_TestContention0_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ContentionTest0Server).TestContention0(&grpc.GenericServerStream[ClientRequest, ClientResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContentionTest0_TestContention0Server = grpc.BidiStreamingServer[ClientRequest, ClientResponse]

func _ContentionTest0_Control_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentionTest0Server).Control(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentionTest0_Control_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentionTest0Server).Control(ctx, req.(*ControlCommand))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentionTest0_ServiceDesc is the grpc.ServiceDesc for ContentionTest0 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentionTest0_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobufs.ContentionTest0",
	HandlerType: (*ContentionTest0Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Control",
			Handler:    _ContentionTest0_Control_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TestContention0",
			Handler:       _ContentionTest0_TestContention0_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "contentiontest.proto",
}

const (
	ContentionTest1_TestContention1_FullMethodName = "/protobufs.ContentionTest1/TestContention1"
	ContentionTest1_Control_FullMethodName         = "/protobufs.ContentionTest1/Control"
)

// ContentionTest1Client is the client API for ContentionTest1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentionTest1Client interface {
	TestContention1(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientRequest, ClientResponse], error)
	Control(ctx context.Context, in *ControlCommand, opts ...grpc.CallOption) (*ControlResponse, error)
}

type contentionTest1Client struct {
	cc grpc.ClientConnInterface
}

func NewContentionTest1Client(cc grpc.ClientConnInterface) ContentionTest1Client {
	return &contentionTest1Client{cc}
}

func (c *contentionTest1Client) TestContention1(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientRequest, ClientResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContentionTest1_ServiceDesc.Streams[0], ContentionTest1_TestContention1_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientRequest, ClientResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContentionTest1_TestContention1Client = grpc.BidiStreamingClient[ClientRequest, ClientResponse]

func (c *contentionTest1Client) Control(ctx context.Context, in *ControlCommand, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, ContentionTest1_Control_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentionTest1Server is the server API for ContentionTest1 service.
// All implementations must embed UnimplementedContentionTest1Server
// for forward compatibility.
type ContentionTest1Server interface {
	TestContention1(grpc.BidiStreamingServer[ClientRequest, ClientResponse]) error
	Control(context.Context, *ControlCommand) (*ControlResponse, error)
	mustEmbedUnimplementedContentionTest1Server()
}

// UnimplementedContentionTest1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentionTest1Server struct{}

func (UnimplementedContentionTest1Server) TestContention1(grpc.BidiStreamingServer[ClientRequest, ClientResponse]) error {
	return status.Errorf(codes.Unimplemented, "method TestContention1 not implemented")
}
func (UnimplementedContentionTest1Server) Control(context.Context, *ControlCommand) (*ControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedContentionTest1Server) mustEmbedUnimplementedContentionTest1Server() {}
func (UnimplementedContentionTest1Server) testEmbeddedByValue()                         {}

// UnsafeContentionTest1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentionTest1Server will
// result in compilation errors.
type UnsafeContentionTest1Server interface {
	mustEmbedUnimplementedContentionTest1Server()
}

func RegisterContentionTest1Server(s grpc.ServiceRegistrar, srv ContentionTest1Server) {
	// If the following call pancis, it indicates UnimplementedContentionTest1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentionTest1_ServiceDesc, srv)
}

func _ContentionTest1_TestContention1_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ContentionTest1Server).TestContention1(&grpc.GenericServerStream[ClientRequest, ClientResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContentionTest1_TestContention1Server = grpc.BidiStreamingServer[ClientRequest, ClientResponse]

func _ContentionTest1_Control_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentionTest1Server).Control(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentionTest1_Control_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentionTest1Server).Control(ctx, req.(*ControlCommand))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentionTest1_ServiceDesc is the grpc.ServiceDesc for ContentionTest1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentionTest1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobufs.ContentionTest1",
	HandlerType: (*ContentionTest1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Control",
			Handler:    _ContentionTest1_Control_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TestContention1",
			Handler:       _ContentionTest1_TestContention1_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "contentiontest.proto",
}

const (
	ContentionTestControl_Control_FullMethodName = "/protobufs.ContentionTestControl/Control"
)

// ContentionTestControlClient is the client API for ContentionTestControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContentionTestControlClient interface {
	Control(ctx context.Context, in *ControlCommand, opts ...grpc.CallOption) (*ControlResponse, error)
}

type contentionTestControlClient struct {
	cc grpc.ClientConnInterface
}

func NewContentionTestControlClient(cc grpc.ClientConnInterface) ContentionTestControlClient {
	return &contentionTestControlClient{cc}
}

func (c *contentionTestControlClient) Control(ctx context.Context, in *ControlCommand, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, ContentionTestControl_Control_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentionTestControlServer is the server API for ContentionTestControl service.
// All implementations must embed UnimplementedContentionTestControlServer
// for forward compatibility.
type ContentionTestControlServer interface {
	Control(context.Context, *ControlCommand) (*ControlResponse, error)
	mustEmbedUnimplementedContentionTestControlServer()
}

// UnimplementedContentionTestControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentionTestControlServer struct{}

func (UnimplementedContentionTestControlServer) Control(context.Context, *ControlCommand) (*ControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedContentionTestControlServer) mustEmbedUnimplementedContentionTestControlServer() {}
func (UnimplementedContentionTestControlServer) testEmbeddedByValue()                               {}

// UnsafeContentionTestControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentionTestControlServer will
// result in compilation errors.
type UnsafeContentionTestControlServer interface {
	mustEmbedUnimplementedContentionTestControlServer()
}

func RegisterContentionTestControlServer(s grpc.ServiceRegistrar, srv ContentionTestControlServer) {
	// If the following call pancis, it indicates UnimplementedContentionTestControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentionTestControl_ServiceDesc, srv)
}

func _ContentionTestControl_Control_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentionTestControlServer).Control(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentionTestControl_Control_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentionTestControlServer).Control(ctx, req.(*ControlCommand))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentionTestControl_ServiceDesc is the grpc.ServiceDesc for ContentionTestControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentionTestControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobufs.ContentionTestControl",
	HandlerType: (*ContentionTestControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Control",
			Handler:    _ContentionTestControl_Control_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contentiontest.proto",
}
