// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.27.2
// source: messenger.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Sn       int32                  `protobuf:"varint,2,opt,name=sn,proto3" json:"sn,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ProtocolMessage_Preprepare
	//	*ProtocolMessage_Prepare
	//	*ProtocolMessage_Commit
	//	*ProtocolMessage_PbftCheckpoint
	//	*ProtocolMessage_Viewchange
	//	*ProtocolMessage_MissingPreprepareReq
	//	*ProtocolMessage_MissingPreprepare
	//	*ProtocolMessage_Newview
	//	*ProtocolMessage_Proposal
	//	*ProtocolMessage_Vote
	//	*ProtocolMessage_Timeout
	//	*ProtocolMessage_Newseqno
	//	*ProtocolMessage_Checkpoint
	//	*ProtocolMessage_Dummy
	//	*ProtocolMessage_Multi
	//	*ProtocolMessage_BandwidthTest
	//	*ProtocolMessage_Close
	//	*ProtocolMessage_RaftVoteRequest
	//	*ProtocolMessage_RaftVoteResponse
	//	*ProtocolMessage_RaftAppendEntryRequest
	//	*ProtocolMessage_RaftAppendEntryResponse
	//	*ProtocolMessage_RaftNewseqno
	//	*ProtocolMessage_MissingEntryReq
	//	*ProtocolMessage_MissingEntry
	//	*ProtocolMessage_PbftCatchup
	//	*ProtocolMessage_HotstuffNewview
	//	*ProtocolMessage_Multipaxos
	Msg           isProtocolMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolMessage) Reset() {
	*x = ProtocolMessage{}
	mi := &file_messenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolMessage) ProtoMessage() {}

func (x *ProtocolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolMessage.ProtoReflect.Descriptor instead.
func (*ProtocolMessage) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolMessage) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ProtocolMessage) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *ProtocolMessage) GetMsg() isProtocolMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ProtocolMessage) GetPreprepare() *PbftPreprepare {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Preprepare); ok {
			return x.Preprepare
		}
	}
	return nil
}

func (x *ProtocolMessage) GetPrepare() *PbftPrepare {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Prepare); ok {
			return x.Prepare
		}
	}
	return nil
}

func (x *ProtocolMessage) GetCommit() *PbftCommit {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *ProtocolMessage) GetPbftCheckpoint() *PbftCheckpoint {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_PbftCheckpoint); ok {
			return x.PbftCheckpoint
		}
	}
	return nil
}

func (x *ProtocolMessage) GetViewchange() *SignedMsg {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Viewchange); ok {
			return x.Viewchange
		}
	}
	return nil
}

func (x *ProtocolMessage) GetMissingPreprepareReq() *PbftMissingPreprepareRequest {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_MissingPreprepareReq); ok {
			return x.MissingPreprepareReq
		}
	}
	return nil
}

func (x *ProtocolMessage) GetMissingPreprepare() *PbftMissingPreprepare {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_MissingPreprepare); ok {
			return x.MissingPreprepare
		}
	}
	return nil
}

func (x *ProtocolMessage) GetNewview() *SignedMsg {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Newview); ok {
			return x.Newview
		}
	}
	return nil
}

func (x *ProtocolMessage) GetProposal() *HotStuffProposal {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Proposal); ok {
			return x.Proposal
		}
	}
	return nil
}

func (x *ProtocolMessage) GetVote() *SignedMsg {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Vote); ok {
			return x.Vote
		}
	}
	return nil
}

func (x *ProtocolMessage) GetTimeout() *Timeout {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Timeout); ok {
			return x.Timeout
		}
	}
	return nil
}

func (x *ProtocolMessage) GetNewseqno() *PbftPreprepare {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Newseqno); ok {
			return x.Newseqno
		}
	}
	return nil
}

func (x *ProtocolMessage) GetCheckpoint() *CheckpointMsg {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Checkpoint); ok {
			return x.Checkpoint
		}
	}
	return nil
}

func (x *ProtocolMessage) GetDummy() *DummyOrdererMsg {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Dummy); ok {
			return x.Dummy
		}
	}
	return nil
}

func (x *ProtocolMessage) GetMulti() *ProtocolMessageBatch {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Multi); ok {
			return x.Multi
		}
	}
	return nil
}

func (x *ProtocolMessage) GetBandwidthTest() *BandwidthTest {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_BandwidthTest); ok {
			return x.BandwidthTest
		}
	}
	return nil
}

func (x *ProtocolMessage) GetClose() *CloseConnection {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *ProtocolMessage) GetRaftVoteRequest() *RaftVoteRequest {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_RaftVoteRequest); ok {
			return x.RaftVoteRequest
		}
	}
	return nil
}

func (x *ProtocolMessage) GetRaftVoteResponse() *RaftVoteResponse {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_RaftVoteResponse); ok {
			return x.RaftVoteResponse
		}
	}
	return nil
}

func (x *ProtocolMessage) GetRaftAppendEntryRequest() *RaftAppendEntryRequest {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_RaftAppendEntryRequest); ok {
			return x.RaftAppendEntryRequest
		}
	}
	return nil
}

func (x *ProtocolMessage) GetRaftAppendEntryResponse() *RaftAppendEntryResponse {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_RaftAppendEntryResponse); ok {
			return x.RaftAppendEntryResponse
		}
	}
	return nil
}

func (x *ProtocolMessage) GetRaftNewseqno() *RaftAppendEntryRequest {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_RaftNewseqno); ok {
			return x.RaftNewseqno
		}
	}
	return nil
}

func (x *ProtocolMessage) GetMissingEntryReq() *MissingEntryRequest {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_MissingEntryReq); ok {
			return x.MissingEntryReq
		}
	}
	return nil
}

func (x *ProtocolMessage) GetMissingEntry() *MissingEntry {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_MissingEntry); ok {
			return x.MissingEntry
		}
	}
	return nil
}

func (x *ProtocolMessage) GetPbftCatchup() *PbftCatchUp {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_PbftCatchup); ok {
			return x.PbftCatchup
		}
	}
	return nil
}

func (x *ProtocolMessage) GetHotstuffNewview() *HotStuffNewView {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_HotstuffNewview); ok {
			return x.HotstuffNewview
		}
	}
	return nil
}

func (x *ProtocolMessage) GetMultipaxos() *MPxMsg {
	if x != nil {
		if x, ok := x.Msg.(*ProtocolMessage_Multipaxos); ok {
			return x.Multipaxos
		}
	}
	return nil
}

type isProtocolMessage_Msg interface {
	isProtocolMessage_Msg()
}

type ProtocolMessage_Preprepare struct {
	Preprepare *PbftPreprepare `protobuf:"bytes,3,opt,name=preprepare,proto3,oneof"`
}

type ProtocolMessage_Prepare struct {
	Prepare *PbftPrepare `protobuf:"bytes,4,opt,name=prepare,proto3,oneof"`
}

type ProtocolMessage_Commit struct {
	Commit *PbftCommit `protobuf:"bytes,5,opt,name=commit,proto3,oneof"`
}

type ProtocolMessage_PbftCheckpoint struct {
	PbftCheckpoint *PbftCheckpoint `protobuf:"bytes,6,opt,name=pbft_checkpoint,json=pbftCheckpoint,proto3,oneof"`
}

type ProtocolMessage_Viewchange struct {
	Viewchange *SignedMsg `protobuf:"bytes,7,opt,name=viewchange,proto3,oneof"`
}

type ProtocolMessage_MissingPreprepareReq struct {
	MissingPreprepareReq *PbftMissingPreprepareRequest `protobuf:"bytes,8,opt,name=missing_preprepare_req,json=missingPreprepareReq,proto3,oneof"`
}

type ProtocolMessage_MissingPreprepare struct {
	MissingPreprepare *PbftMissingPreprepare `protobuf:"bytes,9,opt,name=missing_preprepare,json=missingPreprepare,proto3,oneof"`
}

type ProtocolMessage_Newview struct {
	Newview *SignedMsg `protobuf:"bytes,10,opt,name=newview,proto3,oneof"`
}

type ProtocolMessage_Proposal struct {
	Proposal *HotStuffProposal `protobuf:"bytes,11,opt,name=proposal,proto3,oneof"`
}

type ProtocolMessage_Vote struct {
	Vote *SignedMsg `protobuf:"bytes,12,opt,name=vote,proto3,oneof"`
}

type ProtocolMessage_Timeout struct {
	Timeout *Timeout `protobuf:"bytes,13,opt,name=timeout,proto3,oneof"`
}

type ProtocolMessage_Newseqno struct {
	Newseqno *PbftPreprepare `protobuf:"bytes,14,opt,name=newseqno,proto3,oneof"`
}

type ProtocolMessage_Checkpoint struct {
	Checkpoint *CheckpointMsg `protobuf:"bytes,15,opt,name=checkpoint,proto3,oneof"`
}

type ProtocolMessage_Dummy struct {
	Dummy *DummyOrdererMsg `protobuf:"bytes,16,opt,name=dummy,proto3,oneof"`
}

type ProtocolMessage_Multi struct {
	Multi *ProtocolMessageBatch `protobuf:"bytes,17,opt,name=multi,proto3,oneof"`
}

type ProtocolMessage_BandwidthTest struct {
	BandwidthTest *BandwidthTest `protobuf:"bytes,18,opt,name=bandwidth_test,json=bandwidthTest,proto3,oneof"`
}

type ProtocolMessage_Close struct {
	Close *CloseConnection `protobuf:"bytes,19,opt,name=close,proto3,oneof"`
}

type ProtocolMessage_RaftVoteRequest struct {
	RaftVoteRequest *RaftVoteRequest `protobuf:"bytes,20,opt,name=raft_vote_request,json=raftVoteRequest,proto3,oneof"`
}

type ProtocolMessage_RaftVoteResponse struct {
	RaftVoteResponse *RaftVoteResponse `protobuf:"bytes,21,opt,name=raft_vote_response,json=raftVoteResponse,proto3,oneof"`
}

type ProtocolMessage_RaftAppendEntryRequest struct {
	RaftAppendEntryRequest *RaftAppendEntryRequest `protobuf:"bytes,22,opt,name=raft_append_entry_request,json=raftAppendEntryRequest,proto3,oneof"`
}

type ProtocolMessage_RaftAppendEntryResponse struct {
	RaftAppendEntryResponse *RaftAppendEntryResponse `protobuf:"bytes,23,opt,name=raft_append_entry_response,json=raftAppendEntryResponse,proto3,oneof"`
}

type ProtocolMessage_RaftNewseqno struct {
	RaftNewseqno *RaftAppendEntryRequest `protobuf:"bytes,24,opt,name=raft_newseqno,json=raftNewseqno,proto3,oneof"`
}

type ProtocolMessage_MissingEntryReq struct {
	MissingEntryReq *MissingEntryRequest `protobuf:"bytes,25,opt,name=missing_entry_req,json=missingEntryReq,proto3,oneof"`
}

type ProtocolMessage_MissingEntry struct {
	MissingEntry *MissingEntry `protobuf:"bytes,26,opt,name=missing_entry,json=missingEntry,proto3,oneof"`
}

type ProtocolMessage_PbftCatchup struct {
	PbftCatchup *PbftCatchUp `protobuf:"bytes,27,opt,name=pbft_catchup,json=pbftCatchup,proto3,oneof"`
}

type ProtocolMessage_HotstuffNewview struct {
	HotstuffNewview *HotStuffNewView `protobuf:"bytes,28,opt,name=hotstuff_newview,json=hotstuffNewview,proto3,oneof"`
}

type ProtocolMessage_Multipaxos struct {
	Multipaxos *MPxMsg `protobuf:"bytes,30,opt,name=multipaxos,proto3,oneof"`
}

func (*ProtocolMessage_Preprepare) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Prepare) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Commit) isProtocolMessage_Msg() {}

func (*ProtocolMessage_PbftCheckpoint) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Viewchange) isProtocolMessage_Msg() {}

func (*ProtocolMessage_MissingPreprepareReq) isProtocolMessage_Msg() {}

func (*ProtocolMessage_MissingPreprepare) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Newview) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Proposal) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Vote) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Timeout) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Newseqno) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Checkpoint) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Dummy) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Multi) isProtocolMessage_Msg() {}

func (*ProtocolMessage_BandwidthTest) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Close) isProtocolMessage_Msg() {}

func (*ProtocolMessage_RaftVoteRequest) isProtocolMessage_Msg() {}

func (*ProtocolMessage_RaftVoteResponse) isProtocolMessage_Msg() {}

func (*ProtocolMessage_RaftAppendEntryRequest) isProtocolMessage_Msg() {}

func (*ProtocolMessage_RaftAppendEntryResponse) isProtocolMessage_Msg() {}

func (*ProtocolMessage_RaftNewseqno) isProtocolMessage_Msg() {}

func (*ProtocolMessage_MissingEntryReq) isProtocolMessage_Msg() {}

func (*ProtocolMessage_MissingEntry) isProtocolMessage_Msg() {}

func (*ProtocolMessage_PbftCatchup) isProtocolMessage_Msg() {}

func (*ProtocolMessage_HotstuffNewview) isProtocolMessage_Msg() {}

func (*ProtocolMessage_Multipaxos) isProtocolMessage_Msg() {}

type ProtocolMessageBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgs          []*ProtocolMessage     `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolMessageBatch) Reset() {
	*x = ProtocolMessageBatch{}
	mi := &file_messenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolMessageBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolMessageBatch) ProtoMessage() {}

func (x *ProtocolMessageBatch) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolMessageBatch.ProtoReflect.Descriptor instead.
func (*ProtocolMessageBatch) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{1}
}

func (x *ProtocolMessageBatch) GetMsgs() []*ProtocolMessage {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type BandwidthTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandwidthTest) Reset() {
	*x = BandwidthTest{}
	mi := &file_messenger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandwidthTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwidthTest) ProtoMessage() {}

func (x *BandwidthTest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwidthTest.ProtoReflect.Descriptor instead.
func (*BandwidthTest) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{2}
}

func (x *BandwidthTest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type BandwidthTestAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BandwidthTestAck) Reset() {
	*x = BandwidthTestAck{}
	mi := &file_messenger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BandwidthTestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandwidthTestAck) ProtoMessage() {}

func (x *BandwidthTestAck) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandwidthTestAck.ProtoReflect.Descriptor instead.
func (*BandwidthTestAck) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{3}
}

type CloseConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseConnection) Reset() {
	*x = CloseConnection{}
	mi := &file_messenger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnection) ProtoMessage() {}

func (x *CloseConnection) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnection.ProtoReflect.Descriptor instead.
func (*CloseConnection) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{4}
}

var File_messenger_proto protoreflect.FileDescriptor

const file_messenger_proto_rawDesc = "" +
	"\n" +
	"\x0fmessenger.proto\x12\tprotobufs\x1a\x10checkpoint.proto\x1a\x12dummyorderer.proto\x1a\x11pbftorderer.proto\x1a\x15hotstufforderer.proto\x1a\x11raftorderer.proto\x1a\rrequest.proto\x1a\fcommon.proto\x1a\x17multipaxosorderer.proto\"\xa8\x0e\n" +
	"\x0fProtocolMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x0e\n" +
	"\x02sn\x18\x02 \x01(\x05R\x02sn\x12;\n" +
	"\n" +
	"preprepare\x18\x03 \x01(\v2\x19.protobufs.PbftPreprepareH\x00R\n" +
	"preprepare\x122\n" +
	"\aprepare\x18\x04 \x01(\v2\x16.protobufs.PbftPrepareH\x00R\aprepare\x12/\n" +
	"\x06commit\x18\x05 \x01(\v2\x15.protobufs.PbftCommitH\x00R\x06commit\x12D\n" +
	"\x0fpbft_checkpoint\x18\x06 \x01(\v2\x19.protobufs.PbftCheckpointH\x00R\x0epbftCheckpoint\x126\n" +
	"\n" +
	"viewchange\x18\a \x01(\v2\x14.protobufs.SignedMsgH\x00R\n" +
	"viewchange\x12_\n" +
	"\x16missing_preprepare_req\x18\b \x01(\v2'.protobufs.PbftMissingPreprepareRequestH\x00R\x14missingPreprepareReq\x12Q\n" +
	"\x12missing_preprepare\x18\t \x01(\v2 .protobufs.PbftMissingPreprepareH\x00R\x11missingPreprepare\x120\n" +
	"\anewview\x18\n" +
	" \x01(\v2\x14.protobufs.SignedMsgH\x00R\anewview\x129\n" +
	"\bproposal\x18\v \x01(\v2\x1b.protobufs.HotStuffProposalH\x00R\bproposal\x12*\n" +
	"\x04vote\x18\f \x01(\v2\x14.protobufs.SignedMsgH\x00R\x04vote\x12.\n" +
	"\atimeout\x18\r \x01(\v2\x12.protobufs.TimeoutH\x00R\atimeout\x127\n" +
	"\bnewseqno\x18\x0e \x01(\v2\x19.protobufs.PbftPreprepareH\x00R\bnewseqno\x12:\n" +
	"\n" +
	"checkpoint\x18\x0f \x01(\v2\x18.protobufs.CheckpointMsgH\x00R\n" +
	"checkpoint\x122\n" +
	"\x05dummy\x18\x10 \x01(\v2\x1a.protobufs.DummyOrdererMsgH\x00R\x05dummy\x127\n" +
	"\x05multi\x18\x11 \x01(\v2\x1f.protobufs.ProtocolMessageBatchH\x00R\x05multi\x12A\n" +
	"\x0ebandwidth_test\x18\x12 \x01(\v2\x18.protobufs.BandwidthTestH\x00R\rbandwidthTest\x122\n" +
	"\x05close\x18\x13 \x01(\v2\x1a.protobufs.CloseConnectionH\x00R\x05close\x12H\n" +
	"\x11raft_vote_request\x18\x14 \x01(\v2\x1a.protobufs.RaftVoteRequestH\x00R\x0fraftVoteRequest\x12K\n" +
	"\x12raft_vote_response\x18\x15 \x01(\v2\x1b.protobufs.RaftVoteResponseH\x00R\x10raftVoteResponse\x12^\n" +
	"\x19raft_append_entry_request\x18\x16 \x01(\v2!.protobufs.RaftAppendEntryRequestH\x00R\x16raftAppendEntryRequest\x12a\n" +
	"\x1araft_append_entry_response\x18\x17 \x01(\v2\".protobufs.RaftAppendEntryResponseH\x00R\x17raftAppendEntryResponse\x12H\n" +
	"\rraft_newseqno\x18\x18 \x01(\v2!.protobufs.RaftAppendEntryRequestH\x00R\fraftNewseqno\x12L\n" +
	"\x11missing_entry_req\x18\x19 \x01(\v2\x1e.protobufs.MissingEntryRequestH\x00R\x0fmissingEntryReq\x12>\n" +
	"\rmissing_entry\x18\x1a \x01(\v2\x17.protobufs.MissingEntryH\x00R\fmissingEntry\x12;\n" +
	"\fpbft_catchup\x18\x1b \x01(\v2\x16.protobufs.PbftCatchUpH\x00R\vpbftCatchup\x12G\n" +
	"\x10hotstuff_newview\x18\x1c \x01(\v2\x1a.protobufs.HotStuffNewViewH\x00R\x0fhotstuffNewview\x123\n" +
	"\n" +
	"multipaxos\x18\x1e \x01(\v2\x11.protobufs.MPxMsgH\x00R\n" +
	"multipaxosB\x05\n" +
	"\x03msg\"F\n" +
	"\x14ProtocolMessageBatch\x12.\n" +
	"\x04msgs\x18\x01 \x03(\v2\x1a.protobufs.ProtocolMessageR\x04msgs\")\n" +
	"\rBandwidthTest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x12\n" +
	"\x10BandwidthTestAck\"\x11\n" +
	"\x0fCloseConnection2\xe1\x01\n" +
	"\tMessenger\x12E\n" +
	"\x06Listen\x12\x1a.protobufs.ProtocolMessage\x1a\x1b.protobufs.BandwidthTestAck(\x010\x01\x12B\n" +
	"\aRequest\x12\x18.protobufs.ClientRequest\x1a\x19.protobufs.ClientResponse(\x010\x01\x12I\n" +
	"\aBuckets\x12\x1d.protobufs.BucketSubscription\x1a\x1b.protobufs.BucketAssignment(\x010\x01B\x0eZ\f./;protobufsb\x06proto3"

var (
	file_messenger_proto_rawDescOnce sync.Once
	file_messenger_proto_rawDescData []byte
)

func file_messenger_proto_rawDescGZIP() []byte {
	file_messenger_proto_rawDescOnce.Do(func() {
		file_messenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messenger_proto_rawDesc), len(file_messenger_proto_rawDesc)))
	})
	return file_messenger_proto_rawDescData
}

var file_messenger_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_messenger_proto_goTypes = []any{
	(*ProtocolMessage)(nil),              // 0: protobufs.ProtocolMessage
	(*ProtocolMessageBatch)(nil),         // 1: protobufs.ProtocolMessageBatch
	(*BandwidthTest)(nil),                // 2: protobufs.BandwidthTest
	(*BandwidthTestAck)(nil),             // 3: protobufs.BandwidthTestAck
	(*CloseConnection)(nil),              // 4: protobufs.CloseConnection
	(*PbftPreprepare)(nil),               // 5: protobufs.PbftPreprepare
	(*PbftPrepare)(nil),                  // 6: protobufs.PbftPrepare
	(*PbftCommit)(nil),                   // 7: protobufs.PbftCommit
	(*PbftCheckpoint)(nil),               // 8: protobufs.PbftCheckpoint
	(*SignedMsg)(nil),                    // 9: protobufs.SignedMsg
	(*PbftMissingPreprepareRequest)(nil), // 10: protobufs.PbftMissingPreprepareRequest
	(*PbftMissingPreprepare)(nil),        // 11: protobufs.PbftMissingPreprepare
	(*HotStuffProposal)(nil),             // 12: protobufs.HotStuffProposal
	(*Timeout)(nil),                      // 13: protobufs.Timeout
	(*CheckpointMsg)(nil),                // 14: protobufs.CheckpointMsg
	(*DummyOrdererMsg)(nil),              // 15: protobufs.DummyOrdererMsg
	(*RaftVoteRequest)(nil),              // 16: protobufs.RaftVoteRequest
	(*RaftVoteResponse)(nil),             // 17: protobufs.RaftVoteResponse
	(*RaftAppendEntryRequest)(nil),       // 18: protobufs.RaftAppendEntryRequest
	(*RaftAppendEntryResponse)(nil),      // 19: protobufs.RaftAppendEntryResponse
	(*MissingEntryRequest)(nil),          // 20: protobufs.MissingEntryRequest
	(*MissingEntry)(nil),                 // 21: protobufs.MissingEntry
	(*PbftCatchUp)(nil),                  // 22: protobufs.PbftCatchUp
	(*HotStuffNewView)(nil),              // 23: protobufs.HotStuffNewView
	(*MPxMsg)(nil),                       // 24: protobufs.MPxMsg
	(*ClientRequest)(nil),                // 25: protobufs.ClientRequest
	(*BucketSubscription)(nil),           // 26: protobufs.BucketSubscription
	(*ClientResponse)(nil),               // 27: protobufs.ClientResponse
	(*BucketAssignment)(nil),             // 28: protobufs.BucketAssignment
}
var file_messenger_proto_depIdxs = []int32{
	5,  // 0: protobufs.ProtocolMessage.preprepare:type_name -> protobufs.PbftPreprepare
	6,  // 1: protobufs.ProtocolMessage.prepare:type_name -> protobufs.PbftPrepare
	7,  // 2: protobufs.ProtocolMessage.commit:type_name -> protobufs.PbftCommit
	8,  // 3: protobufs.ProtocolMessage.pbft_checkpoint:type_name -> protobufs.PbftCheckpoint
	9,  // 4: protobufs.ProtocolMessage.viewchange:type_name -> protobufs.SignedMsg
	10, // 5: protobufs.ProtocolMessage.missing_preprepare_req:type_name -> protobufs.PbftMissingPreprepareRequest
	11, // 6: protobufs.ProtocolMessage.missing_preprepare:type_name -> protobufs.PbftMissingPreprepare
	9,  // 7: protobufs.ProtocolMessage.newview:type_name -> protobufs.SignedMsg
	12, // 8: protobufs.ProtocolMessage.proposal:type_name -> protobufs.HotStuffProposal
	9,  // 9: protobufs.ProtocolMessage.vote:type_name -> protobufs.SignedMsg
	13, // 10: protobufs.ProtocolMessage.timeout:type_name -> protobufs.Timeout
	5,  // 11: protobufs.ProtocolMessage.newseqno:type_name -> protobufs.PbftPreprepare
	14, // 12: protobufs.ProtocolMessage.checkpoint:type_name -> protobufs.CheckpointMsg
	15, // 13: protobufs.ProtocolMessage.dummy:type_name -> protobufs.DummyOrdererMsg
	1,  // 14: protobufs.ProtocolMessage.multi:type_name -> protobufs.ProtocolMessageBatch
	2,  // 15: protobufs.ProtocolMessage.bandwidth_test:type_name -> protobufs.BandwidthTest
	4,  // 16: protobufs.ProtocolMessage.close:type_name -> protobufs.CloseConnection
	16, // 17: protobufs.ProtocolMessage.raft_vote_request:type_name -> protobufs.RaftVoteRequest
	17, // 18: protobufs.ProtocolMessage.raft_vote_response:type_name -> protobufs.RaftVoteResponse
	18, // 19: protobufs.ProtocolMessage.raft_append_entry_request:type_name -> protobufs.RaftAppendEntryRequest
	19, // 20: protobufs.ProtocolMessage.raft_append_entry_response:type_name -> protobufs.RaftAppendEntryResponse
	18, // 21: protobufs.ProtocolMessage.raft_newseqno:type_name -> protobufs.RaftAppendEntryRequest
	20, // 22: protobufs.ProtocolMessage.missing_entry_req:type_name -> protobufs.MissingEntryRequest
	21, // 23: protobufs.ProtocolMessage.missing_entry:type_name -> protobufs.MissingEntry
	22, // 24: protobufs.ProtocolMessage.pbft_catchup:type_name -> protobufs.PbftCatchUp
	23, // 25: protobufs.ProtocolMessage.hotstuff_newview:type_name -> protobufs.HotStuffNewView
	24, // 26: protobufs.ProtocolMessage.multipaxos:type_name -> protobufs.MPxMsg
	0,  // 27: protobufs.ProtocolMessageBatch.msgs:type_name -> protobufs.ProtocolMessage
	0,  // 28: protobufs.Messenger.Listen:input_type -> protobufs.ProtocolMessage
	25, // 29: protobufs.Messenger.Request:input_type -> protobufs.ClientRequest
	26, // 30: protobufs.Messenger.Buckets:input_type -> protobufs.BucketSubscription
	3,  // 31: protobufs.Messenger.Listen:output_type -> protobufs.BandwidthTestAck
	27, // 32: protobufs.Messenger.Request:output_type -> protobufs.ClientResponse
	28, // 33: protobufs.Messenger.Buckets:output_type -> protobufs.BucketAssignment
	31, // [31:34] is the sub-list for method output_type
	28, // [28:31] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_messenger_proto_init() }
func file_messenger_proto_init() {
	if File_messenger_proto != nil {
		return
	}
	file_checkpoint_proto_init()
	file_dummyorderer_proto_init()
	file_pbftorderer_proto_init()
	file_hotstufforderer_proto_init()
	file_raftorderer_proto_init()
	file_request_proto_init()
	file_common_proto_init()
	file_multipaxosorderer_proto_init()
	file_messenger_proto_msgTypes[0].OneofWrappers = []any{
		(*ProtocolMessage_Preprepare)(nil),
		(*ProtocolMessage_Prepare)(nil),
		(*ProtocolMessage_Commit)(nil),
		(*ProtocolMessage_PbftCheckpoint)(nil),
		(*ProtocolMessage_Viewchange)(nil),
		(*ProtocolMessage_MissingPreprepareReq)(nil),
		(*ProtocolMessage_MissingPreprepare)(nil),
		(*ProtocolMessage_Newview)(nil),
		(*ProtocolMessage_Proposal)(nil),
		(*ProtocolMessage_Vote)(nil),
		(*ProtocolMessage_Timeout)(nil),
		(*ProtocolMessage_Newseqno)(nil),
		(*ProtocolMessage_Checkpoint)(nil),
		(*ProtocolMessage_Dummy)(nil),
		(*ProtocolMessage_Multi)(nil),
		(*ProtocolMessage_BandwidthTest)(nil),
		(*ProtocolMessage_Close)(nil),
		(*ProtocolMessage_RaftVoteRequest)(nil),
		(*ProtocolMessage_RaftVoteResponse)(nil),
		(*ProtocolMessage_RaftAppendEntryRequest)(nil),
		(*ProtocolMessage_RaftAppendEntryResponse)(nil),
		(*ProtocolMessage_RaftNewseqno)(nil),
		(*ProtocolMessage_MissingEntryReq)(nil),
		(*ProtocolMessage_MissingEntry)(nil),
		(*ProtocolMessage_PbftCatchup)(nil),
		(*ProtocolMessage_HotstuffNewview)(nil),
		(*ProtocolMessage_Multipaxos)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messenger_proto_rawDesc), len(file_messenger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messenger_proto_goTypes,
		DependencyIndexes: file_messenger_proto_depIdxs,
		MessageInfos:      file_messenger_proto_msgTypes,
	}.Build()
	File_messenger_proto = out.File
	file_messenger_proto_goTypes = nil
	file_messenger_proto_depIdxs = nil
}
