// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.27.2
// source: nodeidentity.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicAddr    string                 `protobuf:"bytes,2,opt,name=public_addr,json=publicAddr,proto3" json:"public_addr,omitempty"`
	PrivateAddr   string                 `protobuf:"bytes,3,opt,name=private_addr,json=privateAddr,proto3" json:"private_addr,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	PubKey        []byte                 `protobuf:"bytes,5,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_nodeidentity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_nodeidentity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_nodeidentity_proto_rawDescGZIP(), []int{0}
}

func (x *NodeIdentity) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NodeIdentity) GetPublicAddr() string {
	if x != nil {
		return x.PublicAddr
	}
	return ""
}

func (x *NodeIdentity) GetPrivateAddr() string {
	if x != nil {
		return x.PrivateAddr
	}
	return ""
}

func (x *NodeIdentity) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeIdentity) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

var File_nodeidentity_proto protoreflect.FileDescriptor

const file_nodeidentity_proto_rawDesc = "" +
	"\n" +
	"\x12nodeidentity.proto\x12\tprotobufs\"\x98\x01\n" +
	"\fNodeIdentity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1f\n" +
	"\vpublic_addr\x18\x02 \x01(\tR\n" +
	"publicAddr\x12!\n" +
	"\fprivate_addr\x18\x03 \x01(\tR\vprivateAddr\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x17\n" +
	"\apub_key\x18\x05 \x01(\fR\x06pubKeyB\x0eZ\f./;protobufsb\x06proto3"

var (
	file_nodeidentity_proto_rawDescOnce sync.Once
	file_nodeidentity_proto_rawDescData []byte
)

func file_nodeidentity_proto_rawDescGZIP() []byte {
	file_nodeidentity_proto_rawDescOnce.Do(func() {
		file_nodeidentity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeidentity_proto_rawDesc), len(file_nodeidentity_proto_rawDesc)))
	})
	return file_nodeidentity_proto_rawDescData
}

var file_nodeidentity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nodeidentity_proto_goTypes = []any{
	(*NodeIdentity)(nil), // 0: protobufs.NodeIdentity
}
var file_nodeidentity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nodeidentity_proto_init() }
func file_nodeidentity_proto_init() {
	if File_nodeidentity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeidentity_proto_rawDesc), len(file_nodeidentity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nodeidentity_proto_goTypes,
		DependencyIndexes: file_nodeidentity_proto_depIdxs,
		MessageInfos:      file_nodeidentity_proto_msgTypes,
	}.Build()
	File_nodeidentity_proto = out.File
	file_nodeidentity_proto_goTypes = nil
	file_nodeidentity_proto_depIdxs = nil
}
