// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.27.2
// source: raftorderer.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`                                  // candidate's term
	CandidateId   int32                  `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"` // candidate requesting vote
	LastSn        int32                  `protobuf:"varint,3,opt,name=last_sn,json=lastSn,proto3" json:"last_sn,omitempty"`                // sequence number of candidate's last log entry
	LastTerm      int32                  `protobuf:"varint,4,opt,name=last_term,json=lastTerm,proto3" json:"last_term,omitempty"`          // term of candidates's last log entry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftVoteRequest) Reset() {
	*x = RaftVoteRequest{}
	mi := &file_raftorderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftVoteRequest) ProtoMessage() {}

func (x *RaftVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftorderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftVoteRequest.ProtoReflect.Descriptor instead.
func (*RaftVoteRequest) Descriptor() ([]byte, []int) {
	return file_raftorderer_proto_rawDescGZIP(), []int{0}
}

func (x *RaftVoteRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftVoteRequest) GetCandidateId() int32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RaftVoteRequest) GetLastSn() int32 {
	if x != nil {
		return x.LastSn
	}
	return 0
}

func (x *RaftVoteRequest) GetLastTerm() int32 {
	if x != nil {
		return x.LastTerm
	}
	return 0
}

type RaftVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`                                  // current term
	CandidateId   int32                  `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"` // the candidate who requested the vote
	VoteGranted   bool                   `protobuf:"varint,3,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"` // true if the node votes for the candidate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftVoteResponse) Reset() {
	*x = RaftVoteResponse{}
	mi := &file_raftorderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftVoteResponse) ProtoMessage() {}

func (x *RaftVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftorderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftVoteResponse.ProtoReflect.Descriptor instead.
func (*RaftVoteResponse) Descriptor() ([]byte, []int) {
	return file_raftorderer_proto_rawDescGZIP(), []int{1}
}

func (x *RaftVoteResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftVoteResponse) GetCandidateId() int32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RaftVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type RaftAppendEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`                                     // leader's term
	PrevIndex     int32                  `protobuf:"varint,3,opt,name=prev_index,json=prevIndex,proto3" json:"prev_index,omitempty"`          // sequence number of the log entry of the segment immediately preceding
	PrevTerm      int32                  `protobuf:"varint,4,opt,name=prev_term,json=prevTerm,proto3" json:"prev_term,omitempty"`             // term of the previous logged sn
	Batch         *Batch                 `protobuf:"bytes,5,opt,name=batch,proto3" json:"batch,omitempty"`                                    // batch of requests
	LeaderCommit  int32                  `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"` // leader's commit index
	Aborted       bool                   `protobuf:"varint,7,opt,name=aborted,proto3" json:"aborted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAppendEntryRequest) Reset() {
	*x = RaftAppendEntryRequest{}
	mi := &file_raftorderer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAppendEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAppendEntryRequest) ProtoMessage() {}

func (x *RaftAppendEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raftorderer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAppendEntryRequest.ProtoReflect.Descriptor instead.
func (*RaftAppendEntryRequest) Descriptor() ([]byte, []int) {
	return file_raftorderer_proto_rawDescGZIP(), []int{2}
}

func (x *RaftAppendEntryRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftAppendEntryRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftAppendEntryRequest) GetPrevIndex() int32 {
	if x != nil {
		return x.PrevIndex
	}
	return 0
}

func (x *RaftAppendEntryRequest) GetPrevTerm() int32 {
	if x != nil {
		return x.PrevTerm
	}
	return 0
}

func (x *RaftAppendEntryRequest) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *RaftAppendEntryRequest) GetLeaderCommit() int32 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

func (x *RaftAppendEntryRequest) GetAborted() bool {
	if x != nil {
		return x.Aborted
	}
	return false
}

type RaftAppendEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`           // current term for leader to update
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`     // true if the node has a log entry matching the prevSn and prevTerm
	NextIndex     int32                  `protobuf:"varint,4,opt,name=nextIndex,proto3" json:"nextIndex,omitempty"` // the  index the node is expecting next
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAppendEntryResponse) Reset() {
	*x = RaftAppendEntryResponse{}
	mi := &file_raftorderer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAppendEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAppendEntryResponse) ProtoMessage() {}

func (x *RaftAppendEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raftorderer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAppendEntryResponse.ProtoReflect.Descriptor instead.
func (*RaftAppendEntryResponse) Descriptor() ([]byte, []int) {
	return file_raftorderer_proto_rawDescGZIP(), []int{3}
}

func (x *RaftAppendEntryResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RaftAppendEntryResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftAppendEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RaftAppendEntryResponse) GetNextIndex() int32 {
	if x != nil {
		return x.NextIndex
	}
	return 0
}

var File_raftorderer_proto protoreflect.FileDescriptor

const file_raftorderer_proto_rawDesc = "" +
	"\n" +
	"\x11raftorderer.proto\x12\tprotobufs\x1a\rrequest.proto\"~\n" +
	"\x0fRaftVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\x05R\vcandidateId\x12\x17\n" +
	"\alast_sn\x18\x03 \x01(\x05R\x06lastSn\x12\x1b\n" +
	"\tlast_term\x18\x04 \x01(\x05R\blastTerm\"l\n" +
	"\x10RaftVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\x05R\vcandidateId\x12!\n" +
	"\fvote_granted\x18\x03 \x01(\bR\vvoteGranted\"\xe5\x01\n" +
	"\x16RaftAppendEntryRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12\x1d\n" +
	"\n" +
	"prev_index\x18\x03 \x01(\x05R\tprevIndex\x12\x1b\n" +
	"\tprev_term\x18\x04 \x01(\x05R\bprevTerm\x12&\n" +
	"\x05batch\x18\x05 \x01(\v2\x10.protobufs.BatchR\x05batch\x12#\n" +
	"\rleader_commit\x18\x06 \x01(\x05R\fleaderCommit\x12\x18\n" +
	"\aaborted\x18\a \x01(\bR\aaborted\"{\n" +
	"\x17RaftAppendEntryResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1c\n" +
	"\tnextIndex\x18\x04 \x01(\x05R\tnextIndexB\x0eZ\f./;protobufsb\x06proto3"

var (
	file_raftorderer_proto_rawDescOnce sync.Once
	file_raftorderer_proto_rawDescData []byte
)

func file_raftorderer_proto_rawDescGZIP() []byte {
	file_raftorderer_proto_rawDescOnce.Do(func() {
		file_raftorderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raftorderer_proto_rawDesc), len(file_raftorderer_proto_rawDesc)))
	})
	return file_raftorderer_proto_rawDescData
}

var file_raftorderer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_raftorderer_proto_goTypes = []any{
	(*RaftVoteRequest)(nil),         // 0: protobufs.RaftVoteRequest
	(*RaftVoteResponse)(nil),        // 1: protobufs.RaftVoteResponse
	(*RaftAppendEntryRequest)(nil),  // 2: protobufs.RaftAppendEntryRequest
	(*RaftAppendEntryResponse)(nil), // 3: protobufs.RaftAppendEntryResponse
	(*Batch)(nil),                   // 4: protobufs.Batch
}
var file_raftorderer_proto_depIdxs = []int32{
	4, // 0: protobufs.RaftAppendEntryRequest.batch:type_name -> protobufs.Batch
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_raftorderer_proto_init() }
func file_raftorderer_proto_init() {
	if File_raftorderer_proto != nil {
		return
	}
	file_request_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raftorderer_proto_rawDesc), len(file_raftorderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raftorderer_proto_goTypes,
		DependencyIndexes: file_raftorderer_proto_depIdxs,
		MessageInfos:      file_raftorderer_proto_msgTypes,
	}.Build()
	File_raftorderer_proto = out.File
	file_raftorderer_proto_goTypes = nil
	file_raftorderer_proto_depIdxs = nil
}
