// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: multipaxosorderer.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiPaxosOrderer_Step_FullMethodName = "/protobufs.MultiPaxosOrderer/Step"
)

// MultiPaxosOrdererClient is the client API for MultiPaxosOrderer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MultiPaxosOrdererClient interface {
	Step(ctx context.Context, in *MPxMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type multiPaxosOrdererClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiPaxosOrdererClient(cc grpc.ClientConnInterface) MultiPaxosOrdererClient {
	return &multiPaxosOrdererClient{cc}
}

func (c *multiPaxosOrdererClient) Step(ctx context.Context, in *MPxMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MultiPaxosOrderer_Step_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiPaxosOrdererServer is the server API for MultiPaxosOrderer service.
// All implementations must embed UnimplementedMultiPaxosOrdererServer
// for forward compatibility.
type MultiPaxosOrdererServer interface {
	Step(context.Context, *MPxMsg) (*emptypb.Empty, error)
	mustEmbedUnimplementedMultiPaxosOrdererServer()
}

// UnimplementedMultiPaxosOrdererServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiPaxosOrdererServer struct{}

func (UnimplementedMultiPaxosOrdererServer) Step(context.Context, *MPxMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedMultiPaxosOrdererServer) mustEmbedUnimplementedMultiPaxosOrdererServer() {}
func (UnimplementedMultiPaxosOrdererServer) testEmbeddedByValue()                           {}

// UnsafeMultiPaxosOrdererServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiPaxosOrdererServer will
// result in compilation errors.
type UnsafeMultiPaxosOrdererServer interface {
	mustEmbedUnimplementedMultiPaxosOrdererServer()
}

func RegisterMultiPaxosOrdererServer(s grpc.ServiceRegistrar, srv MultiPaxosOrdererServer) {
	// If the following call pancis, it indicates UnimplementedMultiPaxosOrdererServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultiPaxosOrderer_ServiceDesc, srv)
}

func _MultiPaxosOrderer_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MPxMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPaxosOrdererServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiPaxosOrderer_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPaxosOrdererServer).Step(ctx, req.(*MPxMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// MultiPaxosOrderer_ServiceDesc is the grpc.ServiceDesc for MultiPaxosOrderer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiPaxosOrderer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobufs.MultiPaxosOrderer",
	HandlerType: (*MultiPaxosOrdererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Step",
			Handler:    _MultiPaxosOrderer_Step_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multipaxosorderer.proto",
}
