// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: pbftorderer.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbftPreprepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	View          int32                  `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Leader        int32                  `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	Batch         *Batch                 `protobuf:"bytes,4,opt,name=batch,proto3" json:"batch,omitempty"`
	Aborted       bool                   `protobuf:"varint,5,opt,name=aborted,proto3" json:"aborted,omitempty"`
	Ts            int64                  `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"` // Timestamp to be set by the receiver at message reception.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftPreprepare) Reset() {
	*x = PbftPreprepare{}
	mi := &file_pbftorderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftPreprepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftPreprepare) ProtoMessage() {}

func (x *PbftPreprepare) ProtoReflect() protoreflect.Message {
	mi := &file_pbftorderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftPreprepare.ProtoReflect.Descriptor instead.
func (*PbftPreprepare) Descriptor() ([]byte, []int) {
	return file_pbftorderer_proto_rawDescGZIP(), []int{0}
}

func (x *PbftPreprepare) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *PbftPreprepare) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PbftPreprepare) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *PbftPreprepare) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *PbftPreprepare) GetAborted() bool {
	if x != nil {
		return x.Aborted
	}
	return false
}

func (x *PbftPreprepare) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type PbftPrepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	View          int32                  `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftPrepare) Reset() {
	*x = PbftPrepare{}
	mi := &file_pbftorderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftPrepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftPrepare) ProtoMessage() {}

func (x *PbftPrepare) ProtoReflect() protoreflect.Message {
	mi := &file_pbftorderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftPrepare.ProtoReflect.Descriptor instead.
func (*PbftPrepare) Descriptor() ([]byte, []int) {
	return file_pbftorderer_proto_rawDescGZIP(), []int{1}
}

func (x *PbftPrepare) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *PbftPrepare) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PbftPrepare) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type PbftCommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	View          int32                  `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Ts            int64                  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"` // Timestamp to be set by the receiver at message reception.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftCommit) Reset() {
	*x = PbftCommit{}
	mi := &file_pbftorderer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftCommit) ProtoMessage() {}

func (x *PbftCommit) ProtoReflect() protoreflect.Message {
	mi := &file_pbftorderer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftCommit.ProtoReflect.Descriptor instead.
func (*PbftCommit) Descriptor() ([]byte, []int) {
	return file_pbftorderer_proto_rawDescGZIP(), []int{2}
}

func (x *PbftCommit) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *PbftCommit) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PbftCommit) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PbftCommit) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type PbftCheckpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digests       [][]byte               `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftCheckpoint) Reset() {
	*x = PbftCheckpoint{}
	mi := &file_pbftorderer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftCheckpoint) ProtoMessage() {}

func (x *PbftCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_pbftorderer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftCheckpoint.ProtoReflect.Descriptor instead.
func (*PbftCheckpoint) Descriptor() ([]byte, []int) {
	return file_pbftorderer_proto_rawDescGZIP(), []int{3}
}

func (x *PbftCheckpoint) GetDigests() [][]byte {
	if x != nil {
		return x.Digests
	}
	return nil
}

// Not sent over the networ, only used internally by the PBFT instance
type PbftCatchUp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftCatchUp) Reset() {
	*x = PbftCatchUp{}
	mi := &file_pbftorderer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftCatchUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftCatchUp) ProtoMessage() {}

func (x *PbftCatchUp) ProtoReflect() protoreflect.Message {
	mi := &file_pbftorderer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftCatchUp.ProtoReflect.Descriptor instead.
func (*PbftCatchUp) Descriptor() ([]byte, []int) {
	return file_pbftorderer_proto_rawDescGZIP(), []int{4}
}

type PbftViewChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int32                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`                                                                           // new view
	H             int32                  `protobuf:"varint,2,opt,name=h,proto3" json:"h,omitempty"`                                                                                 // latest stable checkpoitn
	Pset          map[int32]*PbftPrepare `protobuf:"bytes,3,rep,name=pset,proto3" json:"pset,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // prepared requests at previous views
	Qset          map[int32]*PbftPrepare `protobuf:"bytes,4,rep,name=qset,proto3" json:"qset,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // preprepared requests at previous views
	Cset          []*CheckpointMsg       `protobuf:"bytes,5,rep,name=cset,proto3" json:"cset,omitempty"`                                                                            // all available checkpoints
	SenderId      int32                  `protobuf:"varint,6,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                                                   // Sender ID for convenience (not strictly needed, since it's part of the ProtocolMessage already)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftViewChange) Reset() {
	*x = PbftViewChange{}
	mi := &file_pbftorderer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftViewChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftViewChange) ProtoMessage() {}

func (x *PbftViewChange) ProtoReflect() protoreflect.Message {
	mi := &file_pbftorderer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftViewChange.ProtoReflect.Descriptor instead.
func (*PbftViewChange) Descriptor() ([]byte, []int) {
	return file_pbftorderer_proto_rawDescGZIP(), []int{5}
}

func (x *PbftViewChange) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PbftViewChange) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *PbftViewChange) GetPset() map[int32]*PbftPrepare {
	if x != nil {
		return x.Pset
	}
	return nil
}

func (x *PbftViewChange) GetQset() map[int32]*PbftPrepare {
	if x != nil {
		return x.Qset
	}
	return nil
}

func (x *PbftViewChange) GetCset() []*CheckpointMsg {
	if x != nil {
		return x.Cset
	}
	return nil
}

func (x *PbftViewChange) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

type PbftMissingPreprepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int32                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftMissingPreprepareRequest) Reset() {
	*x = PbftMissingPreprepareRequest{}
	mi := &file_pbftorderer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftMissingPreprepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftMissingPreprepareRequest) ProtoMessage() {}

func (x *PbftMissingPreprepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pbftorderer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftMissingPreprepareRequest.ProtoReflect.Descriptor instead.
func (*PbftMissingPreprepareRequest) Descriptor() ([]byte, []int) {
	return file_pbftorderer_proto_rawDescGZIP(), []int{6}
}

func (x *PbftMissingPreprepareRequest) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

type PbftMissingPreprepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preprepare    *PbftPreprepare        `protobuf:"bytes,1,opt,name=preprepare,proto3" json:"preprepare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftMissingPreprepare) Reset() {
	*x = PbftMissingPreprepare{}
	mi := &file_pbftorderer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftMissingPreprepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftMissingPreprepare) ProtoMessage() {}

func (x *PbftMissingPreprepare) ProtoReflect() protoreflect.Message {
	mi := &file_pbftorderer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftMissingPreprepare.ProtoReflect.Descriptor instead.
func (*PbftMissingPreprepare) Descriptor() ([]byte, []int) {
	return file_pbftorderer_proto_rawDescGZIP(), []int{7}
}

func (x *PbftMissingPreprepare) GetPreprepare() *PbftPreprepare {
	if x != nil {
		return x.Preprepare
	}
	return nil
}

type PbftNewView struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	View          int32                     `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Vset          map[int32]*SignedMsg      `protobuf:"bytes,2,rep,name=vset,proto3" json:"vset,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Xset          map[int32]*PbftPreprepare `protobuf:"bytes,3,rep,name=xset,proto3" json:"xset,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Checkpoint    *CheckpointMsg            `protobuf:"bytes,4,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftNewView) Reset() {
	*x = PbftNewView{}
	mi := &file_pbftorderer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftNewView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftNewView) ProtoMessage() {}

func (x *PbftNewView) ProtoReflect() protoreflect.Message {
	mi := &file_pbftorderer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftNewView.ProtoReflect.Descriptor instead.
func (*PbftNewView) Descriptor() ([]byte, []int) {
	return file_pbftorderer_proto_rawDescGZIP(), []int{8}
}

func (x *PbftNewView) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PbftNewView) GetVset() map[int32]*SignedMsg {
	if x != nil {
		return x.Vset
	}
	return nil
}

func (x *PbftNewView) GetXset() map[int32]*PbftPreprepare {
	if x != nil {
		return x.Xset
	}
	return nil
}

func (x *PbftNewView) GetCheckpoint() *CheckpointMsg {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

var File_pbftorderer_proto protoreflect.FileDescriptor

const file_pbftorderer_proto_rawDesc = "" +
	"\n" +
	"\x11pbftorderer.proto\x12\tprotobufs\x1a\rrequest.proto\x1a\x10checkpoint.proto\x1a\fcommon.proto\"\x9e\x01\n" +
	"\x0ePbftPreprepare\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12\x12\n" +
	"\x04view\x18\x02 \x01(\x05R\x04view\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\x05R\x06leader\x12&\n" +
	"\x05batch\x18\x04 \x01(\v2\x10.protobufs.BatchR\x05batch\x12\x18\n" +
	"\aaborted\x18\x05 \x01(\bR\aaborted\x12\x0e\n" +
	"\x02ts\x18\x06 \x01(\x03R\x02ts\"I\n" +
	"\vPbftPrepare\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12\x12\n" +
	"\x04view\x18\x02 \x01(\x05R\x04view\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\"X\n" +
	"\n" +
	"PbftCommit\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12\x12\n" +
	"\x04view\x18\x02 \x01(\x05R\x04view\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x03R\x02ts\"*\n" +
	"\x0ePbftCheckpoint\x12\x18\n" +
	"\adigests\x18\x01 \x03(\fR\adigests\"\r\n" +
	"\vPbftCatchUp\"\x91\x03\n" +
	"\x0ePbftViewChange\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x05R\x04view\x12\f\n" +
	"\x01h\x18\x02 \x01(\x05R\x01h\x127\n" +
	"\x04pset\x18\x03 \x03(\v2#.protobufs.PbftViewChange.PsetEntryR\x04pset\x127\n" +
	"\x04qset\x18\x04 \x03(\v2#.protobufs.PbftViewChange.QsetEntryR\x04qset\x12,\n" +
	"\x04cset\x18\x05 \x03(\v2\x18.protobufs.CheckpointMsgR\x04cset\x12\x1b\n" +
	"\tsender_id\x18\x06 \x01(\x05R\bsenderId\x1aO\n" +
	"\tPsetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.protobufs.PbftPrepareR\x05value:\x028\x01\x1aO\n" +
	"\tQsetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.protobufs.PbftPrepareR\x05value:\x028\x01\"2\n" +
	"\x1cPbftMissingPreprepareRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x05R\x04view\"R\n" +
	"\x15PbftMissingPreprepare\x129\n" +
	"\n" +
	"preprepare\x18\x01 \x01(\v2\x19.protobufs.PbftPreprepareR\n" +
	"preprepare\"\xea\x02\n" +
	"\vPbftNewView\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x05R\x04view\x124\n" +
	"\x04vset\x18\x02 \x03(\v2 .protobufs.PbftNewView.VsetEntryR\x04vset\x124\n" +
	"\x04xset\x18\x03 \x03(\v2 .protobufs.PbftNewView.XsetEntryR\x04xset\x128\n" +
	"\n" +
	"checkpoint\x18\x04 \x01(\v2\x18.protobufs.CheckpointMsgR\n" +
	"checkpoint\x1aM\n" +
	"\tVsetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.protobufs.SignedMsgR\x05value:\x028\x01\x1aR\n" +
	"\tXsetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.protobufs.PbftPreprepareR\x05value:\x028\x01B8Z6github.com/hyperledger-labs/mirbft/protobufs;protobufsb\x06proto3"

var (
	file_pbftorderer_proto_rawDescOnce sync.Once
	file_pbftorderer_proto_rawDescData []byte
)

func file_pbftorderer_proto_rawDescGZIP() []byte {
	file_pbftorderer_proto_rawDescOnce.Do(func() {
		file_pbftorderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbftorderer_proto_rawDesc), len(file_pbftorderer_proto_rawDesc)))
	})
	return file_pbftorderer_proto_rawDescData
}

var file_pbftorderer_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pbftorderer_proto_goTypes = []any{
	(*PbftPreprepare)(nil),               // 0: protobufs.PbftPreprepare
	(*PbftPrepare)(nil),                  // 1: protobufs.PbftPrepare
	(*PbftCommit)(nil),                   // 2: protobufs.PbftCommit
	(*PbftCheckpoint)(nil),               // 3: protobufs.PbftCheckpoint
	(*PbftCatchUp)(nil),                  // 4: protobufs.PbftCatchUp
	(*PbftViewChange)(nil),               // 5: protobufs.PbftViewChange
	(*PbftMissingPreprepareRequest)(nil), // 6: protobufs.PbftMissingPreprepareRequest
	(*PbftMissingPreprepare)(nil),        // 7: protobufs.PbftMissingPreprepare
	(*PbftNewView)(nil),                  // 8: protobufs.PbftNewView
	nil,                                  // 9: protobufs.PbftViewChange.PsetEntry
	nil,                                  // 10: protobufs.PbftViewChange.QsetEntry
	nil,                                  // 11: protobufs.PbftNewView.VsetEntry
	nil,                                  // 12: protobufs.PbftNewView.XsetEntry
	(*Batch)(nil),                        // 13: protobufs.Batch
	(*CheckpointMsg)(nil),                // 14: protobufs.CheckpointMsg
	(*SignedMsg)(nil),                    // 15: protobufs.SignedMsg
}
var file_pbftorderer_proto_depIdxs = []int32{
	13, // 0: protobufs.PbftPreprepare.batch:type_name -> protobufs.Batch
	9,  // 1: protobufs.PbftViewChange.pset:type_name -> protobufs.PbftViewChange.PsetEntry
	10, // 2: protobufs.PbftViewChange.qset:type_name -> protobufs.PbftViewChange.QsetEntry
	14, // 3: protobufs.PbftViewChange.cset:type_name -> protobufs.CheckpointMsg
	0,  // 4: protobufs.PbftMissingPreprepare.preprepare:type_name -> protobufs.PbftPreprepare
	11, // 5: protobufs.PbftNewView.vset:type_name -> protobufs.PbftNewView.VsetEntry
	12, // 6: protobufs.PbftNewView.xset:type_name -> protobufs.PbftNewView.XsetEntry
	14, // 7: protobufs.PbftNewView.checkpoint:type_name -> protobufs.CheckpointMsg
	1,  // 8: protobufs.PbftViewChange.PsetEntry.value:type_name -> protobufs.PbftPrepare
	1,  // 9: protobufs.PbftViewChange.QsetEntry.value:type_name -> protobufs.PbftPrepare
	15, // 10: protobufs.PbftNewView.VsetEntry.value:type_name -> protobufs.SignedMsg
	0,  // 11: protobufs.PbftNewView.XsetEntry.value:type_name -> protobufs.PbftPreprepare
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pbftorderer_proto_init() }
func file_pbftorderer_proto_init() {
	if File_pbftorderer_proto != nil {
		return
	}
	file_request_proto_init()
	file_checkpoint_proto_init()
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbftorderer_proto_rawDesc), len(file_pbftorderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbftorderer_proto_goTypes,
		DependencyIndexes: file_pbftorderer_proto_depIdxs,
		MessageInfos:      file_pbftorderer_proto_msgTypes,
	}.Build()
	File_pbftorderer_proto = out.File
	file_pbftorderer_proto_goTypes = nil
	file_pbftorderer_proto_depIdxs = nil
}
