// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: checkpoint.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckpointMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointMsg) Reset() {
	*x = CheckpointMsg{}
	mi := &file_checkpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointMsg) ProtoMessage() {}

func (x *CheckpointMsg) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointMsg.ProtoReflect.Descriptor instead.
func (*CheckpointMsg) Descriptor() ([]byte, []int) {
	return file_checkpoint_proto_rawDescGZIP(), []int{0}
}

func (x *CheckpointMsg) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *CheckpointMsg) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *CheckpointMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type StableCheckpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Proof         map[int32][]byte       `protobuf:"bytes,2,rep,name=proof,proto3" json:"proof,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StableCheckpoint) Reset() {
	*x = StableCheckpoint{}
	mi := &file_checkpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StableCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StableCheckpoint) ProtoMessage() {}

func (x *StableCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_checkpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StableCheckpoint.ProtoReflect.Descriptor instead.
func (*StableCheckpoint) Descriptor() ([]byte, []int) {
	return file_checkpoint_proto_rawDescGZIP(), []int{1}
}

func (x *StableCheckpoint) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *StableCheckpoint) GetProof() map[int32][]byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

var File_checkpoint_proto protoreflect.FileDescriptor

const file_checkpoint_proto_rawDesc = "" +
	"\n" +
	"\x10checkpoint.proto\x12\tprotobufs\"U\n" +
	"\rCheckpointMsg\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\x9a\x01\n" +
	"\x10StableCheckpoint\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12<\n" +
	"\x05proof\x18\x02 \x03(\v2&.protobufs.StableCheckpoint.ProofEntryR\x05proof\x1a8\n" +
	"\n" +
	"ProofEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B8Z6github.com/hyperledger-labs/mirbft/protobufs;protobufsb\x06proto3"

var (
	file_checkpoint_proto_rawDescOnce sync.Once
	file_checkpoint_proto_rawDescData []byte
)

func file_checkpoint_proto_rawDescGZIP() []byte {
	file_checkpoint_proto_rawDescOnce.Do(func() {
		file_checkpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checkpoint_proto_rawDesc), len(file_checkpoint_proto_rawDesc)))
	})
	return file_checkpoint_proto_rawDescData
}

var file_checkpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_checkpoint_proto_goTypes = []any{
	(*CheckpointMsg)(nil),    // 0: protobufs.CheckpointMsg
	(*StableCheckpoint)(nil), // 1: protobufs.StableCheckpoint
	nil,                      // 2: protobufs.StableCheckpoint.ProofEntry
}
var file_checkpoint_proto_depIdxs = []int32{
	2, // 0: protobufs.StableCheckpoint.proof:type_name -> protobufs.StableCheckpoint.ProofEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_checkpoint_proto_init() }
func file_checkpoint_proto_init() {
	if File_checkpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checkpoint_proto_rawDesc), len(file_checkpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_checkpoint_proto_goTypes,
		DependencyIndexes: file_checkpoint_proto_depIdxs,
		MessageInfos:      file_checkpoint_proto_msgTypes,
	}.Build()
	File_checkpoint_proto = out.File
	file_checkpoint_proto_goTypes = nil
	file_checkpoint_proto_depIdxs = nil
}
