// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: hotstufforderer.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HotStuffNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	View          int32                  `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Parent        []byte                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"` // The digest of the parent node
	Batch         *Batch                 `protobuf:"bytes,4,opt,name=batch,proto3" json:"batch,omitempty"`
	Certificate   *HotStuffQC            `protobuf:"bytes,5,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Aborted       bool                   `protobuf:"varint,6,opt,name=aborted,proto3" json:"aborted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotStuffNode) Reset() {
	*x = HotStuffNode{}
	mi := &file_hotstufforderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotStuffNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotStuffNode) ProtoMessage() {}

func (x *HotStuffNode) ProtoReflect() protoreflect.Message {
	mi := &file_hotstufforderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotStuffNode.ProtoReflect.Descriptor instead.
func (*HotStuffNode) Descriptor() ([]byte, []int) {
	return file_hotstufforderer_proto_rawDescGZIP(), []int{0}
}

func (x *HotStuffNode) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HotStuffNode) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *HotStuffNode) GetParent() []byte {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *HotStuffNode) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *HotStuffNode) GetCertificate() *HotStuffQC {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *HotStuffNode) GetAborted() bool {
	if x != nil {
		return x.Aborted
	}
	return false
}

// Since we keep a fixed leader for the segment, the vote does not contain a full node, just a reference
type HotStuffVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotStuffVote) Reset() {
	*x = HotStuffVote{}
	mi := &file_hotstufforderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotStuffVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotStuffVote) ProtoMessage() {}

func (x *HotStuffVote) ProtoReflect() protoreflect.Message {
	mi := &file_hotstufforderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotStuffVote.ProtoReflect.Descriptor instead.
func (*HotStuffVote) Descriptor() ([]byte, []int) {
	return file_hotstufforderer_proto_rawDescGZIP(), []int{1}
}

func (x *HotStuffVote) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HotStuffVote) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type HotStuffQC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int32                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Node          *HotStuffNode          `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotStuffQC) Reset() {
	*x = HotStuffQC{}
	mi := &file_hotstufforderer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotStuffQC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotStuffQC) ProtoMessage() {}

func (x *HotStuffQC) ProtoReflect() protoreflect.Message {
	mi := &file_hotstufforderer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotStuffQC.ProtoReflect.Descriptor instead.
func (*HotStuffQC) Descriptor() ([]byte, []int) {
	return file_hotstufforderer_proto_rawDescGZIP(), []int{2}
}

func (x *HotStuffQC) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HotStuffQC) GetNode() *HotStuffNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *HotStuffQC) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type HotStuffProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leader        int32                  `protobuf:"varint,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Node          *HotStuffNode          `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotStuffProposal) Reset() {
	*x = HotStuffProposal{}
	mi := &file_hotstufforderer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotStuffProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotStuffProposal) ProtoMessage() {}

func (x *HotStuffProposal) ProtoReflect() protoreflect.Message {
	mi := &file_hotstufforderer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotStuffProposal.ProtoReflect.Descriptor instead.
func (*HotStuffProposal) Descriptor() ([]byte, []int) {
	return file_hotstufforderer_proto_rawDescGZIP(), []int{3}
}

func (x *HotStuffProposal) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *HotStuffProposal) GetNode() *HotStuffNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type HotStuffNewView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          int32                  `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Certificate   *HotStuffQC            `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotStuffNewView) Reset() {
	*x = HotStuffNewView{}
	mi := &file_hotstufforderer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotStuffNewView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotStuffNewView) ProtoMessage() {}

func (x *HotStuffNewView) ProtoReflect() protoreflect.Message {
	mi := &file_hotstufforderer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotStuffNewView.ProtoReflect.Descriptor instead.
func (*HotStuffNewView) Descriptor() ([]byte, []int) {
	return file_hotstufforderer_proto_rawDescGZIP(), []int{4}
}

func (x *HotStuffNewView) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *HotStuffNewView) GetCertificate() *HotStuffQC {
	if x != nil {
		return x.Certificate
	}
	return nil
}

var File_hotstufforderer_proto protoreflect.FileDescriptor

const file_hotstufforderer_proto_rawDesc = "" +
	"\n" +
	"\x15hotstufforderer.proto\x12\tprotobufs\x1a\rrequest.proto\"\xcd\x01\n" +
	"\fHotStuffNode\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12\x12\n" +
	"\x04view\x18\x02 \x01(\x05R\x04view\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\fR\x06parent\x12&\n" +
	"\x05batch\x18\x04 \x01(\v2\x10.protobufs.BatchR\x05batch\x127\n" +
	"\vcertificate\x18\x05 \x01(\v2\x15.protobufs.HotStuffQCR\vcertificate\x12\x18\n" +
	"\aaborted\x18\x06 \x01(\bR\aaborted\">\n" +
	"\fHotStuffVote\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\"o\n" +
	"\n" +
	"HotStuffQC\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x05R\x06height\x12+\n" +
	"\x04node\x18\x02 \x01(\v2\x17.protobufs.HotStuffNodeR\x04node\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"W\n" +
	"\x10HotStuffProposal\x12\x16\n" +
	"\x06leader\x18\x01 \x01(\x05R\x06leader\x12+\n" +
	"\x04node\x18\x02 \x01(\v2\x17.protobufs.HotStuffNodeR\x04node\"^\n" +
	"\x0fHotStuffNewView\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x05R\x04view\x127\n" +
	"\vcertificate\x18\x02 \x01(\v2\x15.protobufs.HotStuffQCR\vcertificateB8Z6github.com/hyperledger-labs/mirbft/protobufs;protobufsb\x06proto3"

var (
	file_hotstufforderer_proto_rawDescOnce sync.Once
	file_hotstufforderer_proto_rawDescData []byte
)

func file_hotstufforderer_proto_rawDescGZIP() []byte {
	file_hotstufforderer_proto_rawDescOnce.Do(func() {
		file_hotstufforderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotstufforderer_proto_rawDesc), len(file_hotstufforderer_proto_rawDesc)))
	})
	return file_hotstufforderer_proto_rawDescData
}

var file_hotstufforderer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hotstufforderer_proto_goTypes = []any{
	(*HotStuffNode)(nil),     // 0: protobufs.HotStuffNode
	(*HotStuffVote)(nil),     // 1: protobufs.HotStuffVote
	(*HotStuffQC)(nil),       // 2: protobufs.HotStuffQC
	(*HotStuffProposal)(nil), // 3: protobufs.HotStuffProposal
	(*HotStuffNewView)(nil),  // 4: protobufs.HotStuffNewView
	(*Batch)(nil),            // 5: protobufs.Batch
}
var file_hotstufforderer_proto_depIdxs = []int32{
	5, // 0: protobufs.HotStuffNode.batch:type_name -> protobufs.Batch
	2, // 1: protobufs.HotStuffNode.certificate:type_name -> protobufs.HotStuffQC
	0, // 2: protobufs.HotStuffQC.node:type_name -> protobufs.HotStuffNode
	0, // 3: protobufs.HotStuffProposal.node:type_name -> protobufs.HotStuffNode
	2, // 4: protobufs.HotStuffNewView.certificate:type_name -> protobufs.HotStuffQC
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_hotstufforderer_proto_init() }
func file_hotstufforderer_proto_init() {
	if File_hotstufforderer_proto != nil {
		return
	}
	file_request_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotstufforderer_proto_rawDesc), len(file_hotstufforderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotstufforderer_proto_goTypes,
		DependencyIndexes: file_hotstufforderer_proto_depIdxs,
		MessageInfos:      file_hotstufforderer_proto_msgTypes,
	}.Build()
	File_hotstufforderer_proto = out.File
	file_hotstufforderer_proto_goTypes = nil
	file_hotstufforderer_proto_depIdxs = nil
}
