// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: discovery.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecSignal_Signum int32

const (
	ExecSignal_DEFAULT ExecSignal_Signum = 0
	ExecSignal_SIGHUP  ExecSignal_Signum = 1
	ExecSignal_SIGINT  ExecSignal_Signum = 2
	ExecSignal_SIGKILL ExecSignal_Signum = 9
	ExecSignal_SIGUSR1 ExecSignal_Signum = 10
	ExecSignal_SIGUSR2 ExecSignal_Signum = 12
	ExecSignal_SIGTERM ExecSignal_Signum = 15
)

// Enum value maps for ExecSignal_Signum.
var (
	ExecSignal_Signum_name = map[int32]string{
		0:  "DEFAULT",
		1:  "SIGHUP",
		2:  "SIGINT",
		9:  "SIGKILL",
		10: "SIGUSR1",
		12: "SIGUSR2",
		15: "SIGTERM",
	}
	ExecSignal_Signum_value = map[string]int32{
		"DEFAULT": 0,
		"SIGHUP":  1,
		"SIGINT":  2,
		"SIGKILL": 9,
		"SIGUSR1": 10,
		"SIGUSR2": 12,
		"SIGTERM": 15,
	}
)

func (x ExecSignal_Signum) Enum() *ExecSignal_Signum {
	p := new(ExecSignal_Signum)
	*p = x
	return p
}

func (x ExecSignal_Signum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecSignal_Signum) Descriptor() protoreflect.EnumDescriptor {
	return file_discovery_proto_enumTypes[0].Descriptor()
}

func (ExecSignal_Signum) Type() protoreflect.EnumType {
	return &file_discovery_proto_enumTypes[0]
}

func (x ExecSignal_Signum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecSignal_Signum.Descriptor instead.
func (ExecSignal_Signum) EnumDescriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{12, 0}
}

type RegisterPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicAddr    string                 `protobuf:"bytes,1,opt,name=public_addr,json=publicAddr,proto3" json:"public_addr,omitempty"`
	PrivateAddr   string                 `protobuf:"bytes,2,opt,name=private_addr,json=privateAddr,proto3" json:"private_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerRequest) Reset() {
	*x = RegisterPeerRequest{}
	mi := &file_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerRequest) ProtoMessage() {}

func (x *RegisterPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerRequest.ProtoReflect.Descriptor instead.
func (*RegisterPeerRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterPeerRequest) GetPublicAddr() string {
	if x != nil {
		return x.PublicAddr
	}
	return ""
}

func (x *RegisterPeerRequest) GetPrivateAddr() string {
	if x != nil {
		return x.PrivateAddr
	}
	return ""
}

// Contains identities of all registered peers and
// a newly assigned ID of the requesting peer.
type RegisterPeerResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NewPeerId        int32                  `protobuf:"varint,1,opt,name=new_peer_id,json=newPeerId,proto3" json:"new_peer_id,omitempty"`
	PrivKey          []byte                 `protobuf:"bytes,2,opt,name=priv_key,json=privKey,proto3" json:"priv_key,omitempty"`
	TblsPubKey       []byte                 `protobuf:"bytes,3,opt,name=tbls_pub_key,json=tblsPubKey,proto3" json:"tbls_pub_key,omitempty"`
	TblsPrivKeyShare []byte                 `protobuf:"bytes,4,opt,name=tbls_priv_key_share,json=tblsPrivKeyShare,proto3" json:"tbls_priv_key_share,omitempty"`
	Peers            []*NodeIdentity        `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterPeerResponse) Reset() {
	*x = RegisterPeerResponse{}
	mi := &file_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerResponse) ProtoMessage() {}

func (x *RegisterPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerResponse.ProtoReflect.Descriptor instead.
func (*RegisterPeerResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPeerResponse) GetNewPeerId() int32 {
	if x != nil {
		return x.NewPeerId
	}
	return 0
}

func (x *RegisterPeerResponse) GetPrivKey() []byte {
	if x != nil {
		return x.PrivKey
	}
	return nil
}

func (x *RegisterPeerResponse) GetTblsPubKey() []byte {
	if x != nil {
		return x.TblsPubKey
	}
	return nil
}

func (x *RegisterPeerResponse) GetTblsPrivKeyShare() []byte {
	if x != nil {
		return x.TblsPrivKeyShare
	}
	return nil
}

func (x *RegisterPeerResponse) GetPeers() []*NodeIdentity {
	if x != nil {
		return x.Peers
	}
	return nil
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int32                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetPeerId() int32 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{3}
}

type RegisterClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientRequest) Reset() {
	*x = RegisterClientRequest{}
	mi := &file_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientRequest) ProtoMessage() {}

func (x *RegisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientRequest.ProtoReflect.Descriptor instead.
func (*RegisterClientRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{4}
}

// Contains identities of all registered peers and
// a newly assigned ID of the requesting client.
type RegisterClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewClientId   int32                  `protobuf:"varint,1,opt,name=new_client_id,json=newClientId,proto3" json:"new_client_id,omitempty"`
	Peers         []*NodeIdentity        `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientResponse) Reset() {
	*x = RegisterClientResponse{}
	mi := &file_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientResponse) ProtoMessage() {}

func (x *RegisterClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientResponse.ProtoReflect.Descriptor instead.
func (*RegisterClientResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterClientResponse) GetNewClientId() int32 {
	if x != nil {
		return x.NewClientId
	}
	return 0
}

func (x *RegisterClientResponse) GetPeers() []*NodeIdentity {
	if x != nil {
		return x.Peers
	}
	return nil
}

type SlaveStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdId         int32                  `protobuf:"varint,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	SlaveId       int32                  `protobuf:"varint,2,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlaveStatus) Reset() {
	*x = SlaveStatus{}
	mi := &file_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlaveStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlaveStatus) ProtoMessage() {}

func (x *SlaveStatus) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlaveStatus.ProtoReflect.Descriptor instead.
func (*SlaveStatus) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *SlaveStatus) GetCmdId() int32 {
	if x != nil {
		return x.CmdId
	}
	return 0
}

func (x *SlaveStatus) GetSlaveId() int32 {
	if x != nil {
		return x.SlaveId
	}
	return 0
}

func (x *SlaveStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SlaveStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SlaveStatus) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type MasterCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	CmdId int32                  `protobuf:"varint,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*MasterCommand_InitSlave
	//	*MasterCommand_ExecStart
	//	*MasterCommand_ExecWait
	//	*MasterCommand_ExecSignal
	//	*MasterCommand_Noop
	//	*MasterCommand_Stop
	Cmd           isMasterCommand_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterCommand) Reset() {
	*x = MasterCommand{}
	mi := &file_discovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterCommand) ProtoMessage() {}

func (x *MasterCommand) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterCommand.ProtoReflect.Descriptor instead.
func (*MasterCommand) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{7}
}

func (x *MasterCommand) GetCmdId() int32 {
	if x != nil {
		return x.CmdId
	}
	return 0
}

func (x *MasterCommand) GetCmd() isMasterCommand_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *MasterCommand) GetInitSlave() *InitSlave {
	if x != nil {
		if x, ok := x.Cmd.(*MasterCommand_InitSlave); ok {
			return x.InitSlave
		}
	}
	return nil
}

func (x *MasterCommand) GetExecStart() *ExecStart {
	if x != nil {
		if x, ok := x.Cmd.(*MasterCommand_ExecStart); ok {
			return x.ExecStart
		}
	}
	return nil
}

func (x *MasterCommand) GetExecWait() *ExecWait {
	if x != nil {
		if x, ok := x.Cmd.(*MasterCommand_ExecWait); ok {
			return x.ExecWait
		}
	}
	return nil
}

func (x *MasterCommand) GetExecSignal() *ExecSignal {
	if x != nil {
		if x, ok := x.Cmd.(*MasterCommand_ExecSignal); ok {
			return x.ExecSignal
		}
	}
	return nil
}

func (x *MasterCommand) GetNoop() *Noop {
	if x != nil {
		if x, ok := x.Cmd.(*MasterCommand_Noop); ok {
			return x.Noop
		}
	}
	return nil
}

func (x *MasterCommand) GetStop() *Stop {
	if x != nil {
		if x, ok := x.Cmd.(*MasterCommand_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

type isMasterCommand_Cmd interface {
	isMasterCommand_Cmd()
}

type MasterCommand_InitSlave struct {
	InitSlave *InitSlave `protobuf:"bytes,2,opt,name=init_slave,json=initSlave,proto3,oneof"`
}

type MasterCommand_ExecStart struct {
	ExecStart *ExecStart `protobuf:"bytes,3,opt,name=exec_start,json=execStart,proto3,oneof"`
}

type MasterCommand_ExecWait struct {
	ExecWait *ExecWait `protobuf:"bytes,4,opt,name=exec_wait,json=execWait,proto3,oneof"`
}

type MasterCommand_ExecSignal struct {
	ExecSignal *ExecSignal `protobuf:"bytes,5,opt,name=exec_signal,json=execSignal,proto3,oneof"`
}

type MasterCommand_Noop struct {
	Noop *Noop `protobuf:"bytes,6,opt,name=noop,proto3,oneof"`
}

type MasterCommand_Stop struct {
	Stop *Stop `protobuf:"bytes,7,opt,name=stop,proto3,oneof"`
}

func (*MasterCommand_InitSlave) isMasterCommand_Cmd() {}

func (*MasterCommand_ExecStart) isMasterCommand_Cmd() {}

func (*MasterCommand_ExecWait) isMasterCommand_Cmd() {}

func (*MasterCommand_ExecSignal) isMasterCommand_Cmd() {}

func (*MasterCommand_Noop) isMasterCommand_Cmd() {}

func (*MasterCommand_Stop) isMasterCommand_Cmd() {}

type InitSlave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlaveId       int32                  `protobuf:"varint,1,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSlave) Reset() {
	*x = InitSlave{}
	mi := &file_discovery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSlave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSlave) ProtoMessage() {}

func (x *InitSlave) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSlave.ProtoReflect.Descriptor instead.
func (*InitSlave) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{8}
}

func (x *InitSlave) GetSlaveId() int32 {
	if x != nil {
		return x.SlaveId
	}
	return 0
}

type ExecStart struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OutputFileName string                 `protobuf:"bytes,2,opt,name=output_file_name,json=outputFileName,proto3" json:"output_file_name,omitempty"`
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_discovery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{9}
}

func (x *ExecStart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecStart) GetOutputFileName() string {
	if x != nil {
		return x.OutputFileName
	}
	return ""
}

func (x *ExecStart) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ExecWait struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeout       int32                  `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecWait) Reset() {
	*x = ExecWait{}
	mi := &file_discovery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecWait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecWait) ProtoMessage() {}

func (x *ExecWait) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecWait.ProtoReflect.Descriptor instead.
func (*ExecWait) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{10}
}

func (x *ExecWait) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type Noop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Noop) Reset() {
	*x = Noop{}
	mi := &file_discovery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Noop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Noop) ProtoMessage() {}

func (x *Noop) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Noop.ProtoReflect.Descriptor instead.
func (*Noop) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{11}
}

type ExecSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signum        ExecSignal_Signum      `protobuf:"varint,1,opt,name=signum,proto3,enum=protobufs.ExecSignal_Signum" json:"signum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecSignal) Reset() {
	*x = ExecSignal{}
	mi := &file_discovery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecSignal) ProtoMessage() {}

func (x *ExecSignal) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecSignal.ProtoReflect.Descriptor instead.
func (*ExecSignal) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{12}
}

func (x *ExecSignal) GetSignum() ExecSignal_Signum {
	if x != nil {
		return x.Signum
	}
	return ExecSignal_DEFAULT
}

type Stop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stop) Reset() {
	*x = Stop{}
	mi := &file_discovery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{13}
}

var File_discovery_proto protoreflect.FileDescriptor

const file_discovery_proto_rawDesc = "" +
	"\n" +
	"\x0fdiscovery.proto\x12\tprotobufs\x1a\x12nodeidentity.proto\"Y\n" +
	"\x13RegisterPeerRequest\x12\x1f\n" +
	"\vpublic_addr\x18\x01 \x01(\tR\n" +
	"publicAddr\x12!\n" +
	"\fprivate_addr\x18\x02 \x01(\tR\vprivateAddr\"\xd1\x01\n" +
	"\x14RegisterPeerResponse\x12\x1e\n" +
	"\vnew_peer_id\x18\x01 \x01(\x05R\tnewPeerId\x12\x19\n" +
	"\bpriv_key\x18\x02 \x01(\fR\aprivKey\x12 \n" +
	"\ftbls_pub_key\x18\x03 \x01(\fR\n" +
	"tblsPubKey\x12-\n" +
	"\x13tbls_priv_key_share\x18\x04 \x01(\fR\x10tblsPrivKeyShare\x12-\n" +
	"\x05peers\x18\x05 \x03(\v2\x17.protobufs.NodeIdentityR\x05peers\"&\n" +
	"\vSyncRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x05R\x06peerId\"\x0e\n" +
	"\fSyncResponse\"\x17\n" +
	"\x15RegisterClientRequest\"k\n" +
	"\x16RegisterClientResponse\x12\"\n" +
	"\rnew_client_id\x18\x01 \x01(\x05R\vnewClientId\x12-\n" +
	"\x05peers\x18\x02 \x03(\v2\x17.protobufs.NodeIdentityR\x05peers\"\x83\x01\n" +
	"\vSlaveStatus\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\x05R\x05cmdId\x12\x19\n" +
	"\bslave_id\x18\x02 \x01(\x05R\aslaveId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\"\xd7\x02\n" +
	"\rMasterCommand\x12\x15\n" +
	"\x06cmd_id\x18\x01 \x01(\x05R\x05cmdId\x125\n" +
	"\n" +
	"init_slave\x18\x02 \x01(\v2\x14.protobufs.InitSlaveH\x00R\tinitSlave\x125\n" +
	"\n" +
	"exec_start\x18\x03 \x01(\v2\x14.protobufs.ExecStartH\x00R\texecStart\x122\n" +
	"\texec_wait\x18\x04 \x01(\v2\x13.protobufs.ExecWaitH\x00R\bexecWait\x128\n" +
	"\vexec_signal\x18\x05 \x01(\v2\x15.protobufs.ExecSignalH\x00R\n" +
	"execSignal\x12%\n" +
	"\x04noop\x18\x06 \x01(\v2\x0f.protobufs.NoopH\x00R\x04noop\x12%\n" +
	"\x04stop\x18\a \x01(\v2\x0f.protobufs.StopH\x00R\x04stopB\x05\n" +
	"\x03cmd\"&\n" +
	"\tInitSlave\x12\x19\n" +
	"\bslave_id\x18\x01 \x01(\x05R\aslaveId\"]\n" +
	"\tExecStart\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x10output_file_name\x18\x02 \x01(\tR\x0eoutputFileName\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\"$\n" +
	"\bExecWait\x12\x18\n" +
	"\atimeout\x18\x01 \x01(\x05R\atimeout\"\x06\n" +
	"\x04Noop\"\xa5\x01\n" +
	"\n" +
	"ExecSignal\x124\n" +
	"\x06signum\x18\x01 \x01(\x0e2\x1c.protobufs.ExecSignal.SignumR\x06signum\"a\n" +
	"\x06Signum\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\n" +
	"\n" +
	"\x06SIGHUP\x10\x01\x12\n" +
	"\n" +
	"\x06SIGINT\x10\x02\x12\v\n" +
	"\aSIGKILL\x10\t\x12\v\n" +
	"\aSIGUSR1\x10\n" +
	"\x12\v\n" +
	"\aSIGUSR2\x10\f\x12\v\n" +
	"\aSIGTERM\x10\x0f\"\x06\n" +
	"\x04Stop2\xb9\x02\n" +
	"\tDiscovery\x12Q\n" +
	"\fRegisterPeer\x12\x1e.protobufs.RegisterPeerRequest\x1a\x1f.protobufs.RegisterPeerResponse\"\x00\x12=\n" +
	"\bSyncPeer\x12\x16.protobufs.SyncRequest\x1a\x17.protobufs.SyncResponse\"\x00\x12W\n" +
	"\x0eRegisterClient\x12 .protobufs.RegisterClientRequest\x1a!.protobufs.RegisterClientResponse\"\x00\x12A\n" +
	"\vNextCommand\x12\x16.protobufs.SlaveStatus\x1a\x18.protobufs.MasterCommand\"\x00B8Z6github.com/hyperledger-labs/mirbft/protobufs;protobufsb\x06proto3"

var (
	file_discovery_proto_rawDescOnce sync.Once
	file_discovery_proto_rawDescData []byte
)

func file_discovery_proto_rawDescGZIP() []byte {
	file_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)))
	})
	return file_discovery_proto_rawDescData
}

var file_discovery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_discovery_proto_goTypes = []any{
	(ExecSignal_Signum)(0),         // 0: protobufs.ExecSignal.Signum
	(*RegisterPeerRequest)(nil),    // 1: protobufs.RegisterPeerRequest
	(*RegisterPeerResponse)(nil),   // 2: protobufs.RegisterPeerResponse
	(*SyncRequest)(nil),            // 3: protobufs.SyncRequest
	(*SyncResponse)(nil),           // 4: protobufs.SyncResponse
	(*RegisterClientRequest)(nil),  // 5: protobufs.RegisterClientRequest
	(*RegisterClientResponse)(nil), // 6: protobufs.RegisterClientResponse
	(*SlaveStatus)(nil),            // 7: protobufs.SlaveStatus
	(*MasterCommand)(nil),          // 8: protobufs.MasterCommand
	(*InitSlave)(nil),              // 9: protobufs.InitSlave
	(*ExecStart)(nil),              // 10: protobufs.ExecStart
	(*ExecWait)(nil),               // 11: protobufs.ExecWait
	(*Noop)(nil),                   // 12: protobufs.Noop
	(*ExecSignal)(nil),             // 13: protobufs.ExecSignal
	(*Stop)(nil),                   // 14: protobufs.Stop
	(*NodeIdentity)(nil),           // 15: protobufs.NodeIdentity
}
var file_discovery_proto_depIdxs = []int32{
	15, // 0: protobufs.RegisterPeerResponse.peers:type_name -> protobufs.NodeIdentity
	15, // 1: protobufs.RegisterClientResponse.peers:type_name -> protobufs.NodeIdentity
	9,  // 2: protobufs.MasterCommand.init_slave:type_name -> protobufs.InitSlave
	10, // 3: protobufs.MasterCommand.exec_start:type_name -> protobufs.ExecStart
	11, // 4: protobufs.MasterCommand.exec_wait:type_name -> protobufs.ExecWait
	13, // 5: protobufs.MasterCommand.exec_signal:type_name -> protobufs.ExecSignal
	12, // 6: protobufs.MasterCommand.noop:type_name -> protobufs.Noop
	14, // 7: protobufs.MasterCommand.stop:type_name -> protobufs.Stop
	0,  // 8: protobufs.ExecSignal.signum:type_name -> protobufs.ExecSignal.Signum
	1,  // 9: protobufs.Discovery.RegisterPeer:input_type -> protobufs.RegisterPeerRequest
	3,  // 10: protobufs.Discovery.SyncPeer:input_type -> protobufs.SyncRequest
	5,  // 11: protobufs.Discovery.RegisterClient:input_type -> protobufs.RegisterClientRequest
	7,  // 12: protobufs.Discovery.NextCommand:input_type -> protobufs.SlaveStatus
	2,  // 13: protobufs.Discovery.RegisterPeer:output_type -> protobufs.RegisterPeerResponse
	4,  // 14: protobufs.Discovery.SyncPeer:output_type -> protobufs.SyncResponse
	6,  // 15: protobufs.Discovery.RegisterClient:output_type -> protobufs.RegisterClientResponse
	8,  // 16: protobufs.Discovery.NextCommand:output_type -> protobufs.MasterCommand
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_discovery_proto_init() }
func file_discovery_proto_init() {
	if File_discovery_proto != nil {
		return
	}
	file_nodeidentity_proto_init()
	file_discovery_proto_msgTypes[7].OneofWrappers = []any{
		(*MasterCommand_InitSlave)(nil),
		(*MasterCommand_ExecStart)(nil),
		(*MasterCommand_ExecWait)(nil),
		(*MasterCommand_ExecSignal)(nil),
		(*MasterCommand_Noop)(nil),
		(*MasterCommand_Stop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_proto_depIdxs,
		EnumInfos:         file_discovery_proto_enumTypes,
		MessageInfos:      file_discovery_proto_msgTypes,
	}.Build()
	File_discovery_proto = out.File
	file_discovery_proto_goTypes = nil
	file_discovery_proto_depIdxs = nil
}
