// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: contentiontest.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlCommand_Cmd int32

const (
	ControlCommand_START_STAT ControlCommand_Cmd = 0
	ControlCommand_STOP_STAT  ControlCommand_Cmd = 1
)

// Enum value maps for ControlCommand_Cmd.
var (
	ControlCommand_Cmd_name = map[int32]string{
		0: "START_STAT",
		1: "STOP_STAT",
	}
	ControlCommand_Cmd_value = map[string]int32{
		"START_STAT": 0,
		"STOP_STAT":  1,
	}
)

func (x ControlCommand_Cmd) Enum() *ControlCommand_Cmd {
	p := new(ControlCommand_Cmd)
	*p = x
	return p
}

func (x ControlCommand_Cmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlCommand_Cmd) Descriptor() protoreflect.EnumDescriptor {
	return file_contentiontest_proto_enumTypes[0].Descriptor()
}

func (ControlCommand_Cmd) Type() protoreflect.EnumType {
	return &file_contentiontest_proto_enumTypes[0]
}

func (x ControlCommand_Cmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlCommand_Cmd.Descriptor instead.
func (ControlCommand_Cmd) EnumDescriptor() ([]byte, []int) {
	return file_contentiontest_proto_rawDescGZIP(), []int{0, 0}
}

type ControlCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           ControlCommand_Cmd     `protobuf:"varint,1,opt,name=cmd,proto3,enum=protobufs.ControlCommand_Cmd" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlCommand) Reset() {
	*x = ControlCommand{}
	mi := &file_contentiontest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlCommand) ProtoMessage() {}

func (x *ControlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_contentiontest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlCommand.ProtoReflect.Descriptor instead.
func (*ControlCommand) Descriptor() ([]byte, []int) {
	return file_contentiontest_proto_rawDescGZIP(), []int{0}
}

func (x *ControlCommand) GetCmd() ControlCommand_Cmd {
	if x != nil {
		return x.Cmd
	}
	return ControlCommand_START_STAT
}

type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_contentiontest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentiontest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_contentiontest_proto_rawDescGZIP(), []int{1}
}

var File_contentiontest_proto protoreflect.FileDescriptor

const file_contentiontest_proto_rawDesc = "" +
	"\n" +
	"\x14contentiontest.proto\x12\tprotobufs\x1a\rrequest.proto\"g\n" +
	"\x0eControlCommand\x12/\n" +
	"\x03cmd\x18\x01 \x01(\x0e2\x1d.protobufs.ControlCommand.CmdR\x03cmd\"$\n" +
	"\x03Cmd\x12\x0e\n" +
	"\n" +
	"START_STAT\x10\x00\x12\r\n" +
	"\tSTOP_STAT\x10\x01\"\x11\n" +
	"\x0fControlResponse2\x9f\x01\n" +
	"\x0fContentionTest0\x12J\n" +
	"\x0fTestContention0\x12\x18.protobufs.ClientRequest\x1a\x19.protobufs.ClientResponse(\x010\x01\x12@\n" +
	"\aControl\x12\x19.protobufs.ControlCommand\x1a\x1a.protobufs.ControlResponse2\x9f\x01\n" +
	"\x0fContentionTest1\x12J\n" +
	"\x0fTestContention1\x12\x18.protobufs.ClientRequest\x1a\x19.protobufs.ClientResponse(\x010\x01\x12@\n" +
	"\aControl\x12\x19.protobufs.ControlCommand\x1a\x1a.protobufs.ControlResponse2Y\n" +
	"\x15ContentionTestControl\x12@\n" +
	"\aControl\x12\x19.protobufs.ControlCommand\x1a\x1a.protobufs.ControlResponseB8Z6github.com/hyperledger-labs/mirbft/protobufs;protobufsb\x06proto3"

var (
	file_contentiontest_proto_rawDescOnce sync.Once
	file_contentiontest_proto_rawDescData []byte
)

func file_contentiontest_proto_rawDescGZIP() []byte {
	file_contentiontest_proto_rawDescOnce.Do(func() {
		file_contentiontest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentiontest_proto_rawDesc), len(file_contentiontest_proto_rawDesc)))
	})
	return file_contentiontest_proto_rawDescData
}

var file_contentiontest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contentiontest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contentiontest_proto_goTypes = []any{
	(ControlCommand_Cmd)(0), // 0: protobufs.ControlCommand.Cmd
	(*ControlCommand)(nil),  // 1: protobufs.ControlCommand
	(*ControlResponse)(nil), // 2: protobufs.ControlResponse
	(*ClientRequest)(nil),   // 3: protobufs.ClientRequest
	(*ClientResponse)(nil),  // 4: protobufs.ClientResponse
}
var file_contentiontest_proto_depIdxs = []int32{
	0, // 0: protobufs.ControlCommand.cmd:type_name -> protobufs.ControlCommand.Cmd
	3, // 1: protobufs.ContentionTest0.TestContention0:input_type -> protobufs.ClientRequest
	1, // 2: protobufs.ContentionTest0.Control:input_type -> protobufs.ControlCommand
	3, // 3: protobufs.ContentionTest1.TestContention1:input_type -> protobufs.ClientRequest
	1, // 4: protobufs.ContentionTest1.Control:input_type -> protobufs.ControlCommand
	1, // 5: protobufs.ContentionTestControl.Control:input_type -> protobufs.ControlCommand
	4, // 6: protobufs.ContentionTest0.TestContention0:output_type -> protobufs.ClientResponse
	2, // 7: protobufs.ContentionTest0.Control:output_type -> protobufs.ControlResponse
	4, // 8: protobufs.ContentionTest1.TestContention1:output_type -> protobufs.ClientResponse
	2, // 9: protobufs.ContentionTest1.Control:output_type -> protobufs.ControlResponse
	2, // 10: protobufs.ContentionTestControl.Control:output_type -> protobufs.ControlResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contentiontest_proto_init() }
func file_contentiontest_proto_init() {
	if File_contentiontest_proto != nil {
		return
	}
	file_request_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentiontest_proto_rawDesc), len(file_contentiontest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_contentiontest_proto_goTypes,
		DependencyIndexes: file_contentiontest_proto_depIdxs,
		EnumInfos:         file_contentiontest_proto_enumTypes,
		MessageInfos:      file_contentiontest_proto_msgTypes,
	}.Build()
	File_contentiontest_proto = out.File
	file_contentiontest_proto_goTypes = nil
	file_contentiontest_proto_depIdxs = nil
}
