// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.27.2
// source: dummyorderer.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DummyOrdererMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Batch         *Batch                 `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyOrdererMsg) Reset() {
	*x = DummyOrdererMsg{}
	mi := &file_dummyorderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyOrdererMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyOrdererMsg) ProtoMessage() {}

func (x *DummyOrdererMsg) ProtoReflect() protoreflect.Message {
	mi := &file_dummyorderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyOrdererMsg.ProtoReflect.Descriptor instead.
func (*DummyOrdererMsg) Descriptor() ([]byte, []int) {
	return file_dummyorderer_proto_rawDescGZIP(), []int{0}
}

func (x *DummyOrdererMsg) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *DummyOrdererMsg) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

var File_dummyorderer_proto protoreflect.FileDescriptor

const file_dummyorderer_proto_rawDesc = "" +
	"\n" +
	"\x12dummyorderer.proto\x12\tprotobufs\x1a\rrequest.proto\"I\n" +
	"\x0fDummyOrdererMsg\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12&\n" +
	"\x05batch\x18\x02 \x01(\v2\x10.protobufs.BatchR\x05batchB\x0eZ\f./;protobufsb\x06proto3"

var (
	file_dummyorderer_proto_rawDescOnce sync.Once
	file_dummyorderer_proto_rawDescData []byte
)

func file_dummyorderer_proto_rawDescGZIP() []byte {
	file_dummyorderer_proto_rawDescOnce.Do(func() {
		file_dummyorderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dummyorderer_proto_rawDesc), len(file_dummyorderer_proto_rawDesc)))
	})
	return file_dummyorderer_proto_rawDescData
}

var file_dummyorderer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dummyorderer_proto_goTypes = []any{
	(*DummyOrdererMsg)(nil), // 0: protobufs.DummyOrdererMsg
	(*Batch)(nil),           // 1: protobufs.Batch
}
var file_dummyorderer_proto_depIdxs = []int32{
	1, // 0: protobufs.DummyOrdererMsg.batch:type_name -> protobufs.Batch
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dummyorderer_proto_init() }
func file_dummyorderer_proto_init() {
	if File_dummyorderer_proto != nil {
		return
	}
	file_request_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dummyorderer_proto_rawDesc), len(file_dummyorderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dummyorderer_proto_goTypes,
		DependencyIndexes: file_dummyorderer_proto_depIdxs,
		MessageInfos:      file_dummyorderer_proto_msgTypes,
	}.Build()
	File_dummyorderer_proto = out.File
	file_dummyorderer_proto_goTypes = nil
	file_dummyorderer_proto_depIdxs = nil
}
