// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: multipaxosorderer.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MPxInstanceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`     // sequence number (slot)
	Lead          uint64                 `protobuf:"varint,2,opt,name=lead,proto3" json:"lead,omitempty"` // líder corrente (informativo)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPxInstanceId) Reset() {
	*x = MPxInstanceId{}
	mi := &file_multipaxosorderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPxInstanceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxInstanceId) ProtoMessage() {}

func (x *MPxInstanceId) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxInstanceId.ProtoReflect.Descriptor instead.
func (*MPxInstanceId) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{0}
}

func (x *MPxInstanceId) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *MPxInstanceId) GetLead() uint64 {
	if x != nil {
		return x.Lead
	}
	return 0
}

type MPxValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *MPxInstanceId         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Batch         []byte                 `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"` // bytes do protobufs.Batch (serializado)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPxValue) Reset() {
	*x = MPxValue{}
	mi := &file_multipaxosorderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPxValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxValue) ProtoMessage() {}

func (x *MPxValue) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxValue.ProtoReflect.Descriptor instead.
func (*MPxValue) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{1}
}

func (x *MPxValue) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxValue) GetBatch() []byte {
	if x != nil {
		return x.Batch
	}
	return nil
}

type MPxPrepare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *MPxInstanceId         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ballot        uint64                 `protobuf:"varint,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	GroupId       uint32                 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // grupo do batch (bucket)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPxPrepare) Reset() {
	*x = MPxPrepare{}
	mi := &file_multipaxosorderer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPxPrepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxPrepare) ProtoMessage() {}

func (x *MPxPrepare) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxPrepare.ProtoReflect.Descriptor instead.
func (*MPxPrepare) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{2}
}

func (x *MPxPrepare) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxPrepare) GetBallot() uint64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *MPxPrepare) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type MPxPromise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *MPxInstanceId         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ballot        uint64                 `protobuf:"varint,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Value         *MPxValue              `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`                     // valor previamente aceito (se houver)
	GroupId       uint32                 `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 0 = “all”/desconhecido
	Members       []uint32               `protobuf:"varint,6,rep,packed,name=members,proto3" json:"members,omitempty"`         // nós sugeridos por este seguidor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPxPromise) Reset() {
	*x = MPxPromise{}
	mi := &file_multipaxosorderer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPxPromise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxPromise) ProtoMessage() {}

func (x *MPxPromise) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxPromise.ProtoReflect.Descriptor instead.
func (*MPxPromise) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{3}
}

func (x *MPxPromise) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxPromise) GetBallot() uint64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *MPxPromise) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MPxPromise) GetValue() *MPxValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MPxPromise) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MPxPromise) GetMembers() []uint32 {
	if x != nil {
		return x.Members
	}
	return nil
}

type MPxAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *MPxInstanceId         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ballot        uint64                 `protobuf:"varint,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Value         *MPxValue              `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	GroupId       uint32                 `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // grupo decidido pelo líder (informativo)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPxAccept) Reset() {
	*x = MPxAccept{}
	mi := &file_multipaxosorderer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPxAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxAccept) ProtoMessage() {}

func (x *MPxAccept) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxAccept.ProtoReflect.Descriptor instead.
func (*MPxAccept) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{4}
}

func (x *MPxAccept) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxAccept) GetBallot() uint64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *MPxAccept) GetValue() *MPxValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MPxAccept) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type MPxAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *MPxInstanceId         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ballot        uint64                 `protobuf:"varint,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	GroupId       uint32                 `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPxAccepted) Reset() {
	*x = MPxAccepted{}
	mi := &file_multipaxosorderer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPxAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxAccepted) ProtoMessage() {}

func (x *MPxAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxAccepted.ProtoReflect.Descriptor instead.
func (*MPxAccepted) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{5}
}

func (x *MPxAccepted) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxAccepted) GetBallot() uint64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *MPxAccepted) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MPxAccepted) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type MPxCommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *MPxInstanceId         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         *MPxValue              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                     // ausente => NIL (⊥)
	GroupId       uint32                 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // informativo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPxCommit) Reset() {
	*x = MPxCommit{}
	mi := &file_multipaxosorderer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPxCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxCommit) ProtoMessage() {}

func (x *MPxCommit) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxCommit.ProtoReflect.Descriptor instead.
func (*MPxCommit) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{6}
}

func (x *MPxCommit) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxCommit) GetValue() *MPxValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MPxCommit) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type MPxMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*MPxMsg_Prepare
	//	*MPxMsg_Promise
	//	*MPxMsg_Accept
	//	*MPxMsg_Accepted
	//	*MPxMsg_Commit
	Type          isMPxMsg_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPxMsg) Reset() {
	*x = MPxMsg{}
	mi := &file_multipaxosorderer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxMsg) ProtoMessage() {}

func (x *MPxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxMsg.ProtoReflect.Descriptor instead.
func (*MPxMsg) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{7}
}

func (x *MPxMsg) GetType() isMPxMsg_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *MPxMsg) GetPrepare() *MPxPrepare {
	if x != nil {
		if x, ok := x.Type.(*MPxMsg_Prepare); ok {
			return x.Prepare
		}
	}
	return nil
}

func (x *MPxMsg) GetPromise() *MPxPromise {
	if x != nil {
		if x, ok := x.Type.(*MPxMsg_Promise); ok {
			return x.Promise
		}
	}
	return nil
}

func (x *MPxMsg) GetAccept() *MPxAccept {
	if x != nil {
		if x, ok := x.Type.(*MPxMsg_Accept); ok {
			return x.Accept
		}
	}
	return nil
}

func (x *MPxMsg) GetAccepted() *MPxAccepted {
	if x != nil {
		if x, ok := x.Type.(*MPxMsg_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *MPxMsg) GetCommit() *MPxCommit {
	if x != nil {
		if x, ok := x.Type.(*MPxMsg_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

type isMPxMsg_Type interface {
	isMPxMsg_Type()
}

type MPxMsg_Prepare struct {
	Prepare *MPxPrepare `protobuf:"bytes,1,opt,name=prepare,proto3,oneof"`
}

type MPxMsg_Promise struct {
	Promise *MPxPromise `protobuf:"bytes,2,opt,name=promise,proto3,oneof"`
}

type MPxMsg_Accept struct {
	Accept *MPxAccept `protobuf:"bytes,3,opt,name=accept,proto3,oneof"`
}

type MPxMsg_Accepted struct {
	Accepted *MPxAccepted `protobuf:"bytes,4,opt,name=accepted,proto3,oneof"`
}

type MPxMsg_Commit struct {
	Commit *MPxCommit `protobuf:"bytes,5,opt,name=commit,proto3,oneof"`
}

func (*MPxMsg_Prepare) isMPxMsg_Type() {}

func (*MPxMsg_Promise) isMPxMsg_Type() {}

func (*MPxMsg_Accept) isMPxMsg_Type() {}

func (*MPxMsg_Accepted) isMPxMsg_Type() {}

func (*MPxMsg_Commit) isMPxMsg_Type() {}

var File_multipaxosorderer_proto protoreflect.FileDescriptor

const file_multipaxosorderer_proto_rawDesc = "" +
	"\n" +
	"\x17multipaxosorderer.proto\x12\tprotobufs\"3\n" +
	"\rMPxInstanceId\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12\x12\n" +
	"\x04lead\x18\x02 \x01(\x04R\x04lead\"J\n" +
	"\bMPxValue\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.protobufs.MPxInstanceIdR\x02id\x12\x14\n" +
	"\x05batch\x18\x02 \x01(\fR\x05batch\"N\n" +
	"\n" +
	"MPxPrepare\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.protobufs.MPxInstanceIdR\x02id\x12\x16\n" +
	"\x06ballot\x18\x02 \x01(\x04R\x06ballot\"\xbe\x01\n" +
	"\n" +
	"MPxPromise\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.protobufs.MPxInstanceIdR\x02id\x12\x16\n" +
	"\x06ballot\x18\x02 \x01(\x04R\x06ballot\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12)\n" +
	"\x05value\x18\x04 \x01(\v2\x13.protobufs.MPxValueR\x05value\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\rR\agroupId\x12\x18\n" +
	"\amembers\x18\x06 \x03(\rR\amembers\"\x93\x01\n" +
	"\tMPxAccept\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.protobufs.MPxInstanceIdR\x02id\x12\x16\n" +
	"\x06ballot\x18\x02 \x01(\x04R\x06ballot\x12)\n" +
	"\x05value\x18\x03 \x01(\v2\x13.protobufs.MPxValueR\x05value\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\rR\agroupId\"_\n" +
	"\vMPxAccepted\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.protobufs.MPxInstanceIdR\x02id\x12\x16\n" +
	"\x06ballot\x18\x02 \x01(\x04R\x06ballot\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\"{\n" +
	"\tMPxCommit\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.protobufs.MPxInstanceIdR\x02id\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.protobufs.MPxValueR\x05value\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\rR\agroupId\"\x8c\x02\n" +
	"\x06MPxMsg\x121\n" +
	"\aprepare\x18\x01 \x01(\v2\x15.protobufs.MPxPrepareH\x00R\aprepare\x121\n" +
	"\apromise\x18\x02 \x01(\v2\x15.protobufs.MPxPromiseH\x00R\apromise\x12.\n" +
	"\x06accept\x18\x03 \x01(\v2\x14.protobufs.MPxAcceptH\x00R\x06accept\x124\n" +
	"\baccepted\x18\x04 \x01(\v2\x16.protobufs.MPxAcceptedH\x00R\baccepted\x12.\n" +
	"\x06commit\x18\x05 \x01(\v2\x14.protobufs.MPxCommitH\x00R\x06commitB\x06\n" +
	"\x04typeB8Z6github.com/hyperledger-labs/mirbft/protobufs;protobufsb\x06proto3"

var (
	file_multipaxosorderer_proto_rawDescOnce sync.Once
	file_multipaxosorderer_proto_rawDescData []byte
)

func file_multipaxosorderer_proto_rawDescGZIP() []byte {
	file_multipaxosorderer_proto_rawDescOnce.Do(func() {
		file_multipaxosorderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multipaxosorderer_proto_rawDesc), len(file_multipaxosorderer_proto_rawDesc)))
	})
	return file_multipaxosorderer_proto_rawDescData
}

var file_multipaxosorderer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_multipaxosorderer_proto_goTypes = []any{
	(*MPxInstanceId)(nil), // 0: protobufs.MPxInstanceId
	(*MPxValue)(nil),      // 1: protobufs.MPxValue
	(*MPxPrepare)(nil),    // 2: protobufs.MPxPrepare
	(*MPxPromise)(nil),    // 3: protobufs.MPxPromise
	(*MPxAccept)(nil),     // 4: protobufs.MPxAccept
	(*MPxAccepted)(nil),   // 5: protobufs.MPxAccepted
	(*MPxCommit)(nil),     // 6: protobufs.MPxCommit
	(*MPxMsg)(nil),        // 7: protobufs.MPxMsg
}
var file_multipaxosorderer_proto_depIdxs = []int32{
	0,  // 0: protobufs.MPxValue.id:type_name -> protobufs.MPxInstanceId
	0,  // 1: protobufs.MPxPrepare.id:type_name -> protobufs.MPxInstanceId
	0,  // 2: protobufs.MPxPromise.id:type_name -> protobufs.MPxInstanceId
	1,  // 3: protobufs.MPxPromise.value:type_name -> protobufs.MPxValue
	0,  // 4: protobufs.MPxAccept.id:type_name -> protobufs.MPxInstanceId
	1,  // 5: protobufs.MPxAccept.value:type_name -> protobufs.MPxValue
	0,  // 6: protobufs.MPxAccepted.id:type_name -> protobufs.MPxInstanceId
	0,  // 7: protobufs.MPxCommit.id:type_name -> protobufs.MPxInstanceId
	1,  // 8: protobufs.MPxCommit.value:type_name -> protobufs.MPxValue
	2,  // 9: protobufs.MPxMsg.prepare:type_name -> protobufs.MPxPrepare
	3,  // 10: protobufs.MPxMsg.promise:type_name -> protobufs.MPxPromise
	4,  // 11: protobufs.MPxMsg.accept:type_name -> protobufs.MPxAccept
	5,  // 12: protobufs.MPxMsg.accepted:type_name -> protobufs.MPxAccepted
	6,  // 13: protobufs.MPxMsg.commit:type_name -> protobufs.MPxCommit
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_multipaxosorderer_proto_init() }
func file_multipaxosorderer_proto_init() {
	if File_multipaxosorderer_proto != nil {
		return
	}
	file_multipaxosorderer_proto_msgTypes[7].OneofWrappers = []any{
		(*MPxMsg_Prepare)(nil),
		(*MPxMsg_Promise)(nil),
		(*MPxMsg_Accept)(nil),
		(*MPxMsg_Accepted)(nil),
		(*MPxMsg_Commit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multipaxosorderer_proto_rawDesc), len(file_multipaxosorderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multipaxosorderer_proto_goTypes,
		DependencyIndexes: file_multipaxosorderer_proto_depIdxs,
		MessageInfos:      file_multipaxosorderer_proto_msgTypes,
	}.Build()
	File_multipaxosorderer_proto = out.File
	file_multipaxosorderer_proto_goTypes = nil
	file_multipaxosorderer_proto_depIdxs = nil
}
