// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: multipaxosorderer.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MPxInstanceId - Unique identifier for a MultiPaxos consensus instance
type MPxInstanceId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn   int32  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`     // Sequence number
	Lead uint64 `protobuf:"varint,2,opt,name=lead,proto3" json:"lead,omitempty"` // Leader node ID
}

func (x *MPxInstanceId) Reset() {
	*x = MPxInstanceId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxosorderer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPxInstanceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxInstanceId) ProtoMessage() {}

func (x *MPxInstanceId) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxInstanceId.ProtoReflect.Descriptor instead.
func (*MPxInstanceId) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{0}
}

func (x *MPxInstanceId) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *MPxInstanceId) GetLead() uint64 {
	if x != nil {
		return x.Lead
	}
	return 0
}

// MPxValue - Consensus value wrapper (internal use only)
type MPxValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *MPxInstanceId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Batch  *Batch         `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`   // Direct Batch reference (never serialized to preserve signatures)
	Digest []byte         `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"` // SHA-256 digest for validation
}

func (x *MPxValue) Reset() {
	*x = MPxValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxosorderer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPxValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxValue) ProtoMessage() {}

func (x *MPxValue) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxValue.ProtoReflect.Descriptor instead.
func (*MPxValue) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{1}
}

func (x *MPxValue) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxValue) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *MPxValue) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

// MPxPrepare - Phase 1a: Leader requests permission to propose
type MPxPrepare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *MPxInstanceId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ballot  uint64         `protobuf:"varint,2,opt,name=ballot,proto3" json:"ballot,omitempty"`                  // Ballot number (higher = newer round)
	GroupId uint32         `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // Consensus group ID
}

func (x *MPxPrepare) Reset() {
	*x = MPxPrepare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxosorderer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPxPrepare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxPrepare) ProtoMessage() {}

func (x *MPxPrepare) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxPrepare.ProtoReflect.Descriptor instead.
func (*MPxPrepare) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{2}
}

func (x *MPxPrepare) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxPrepare) GetBallot() uint64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *MPxPrepare) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// MPxPromise - Phase 1b: Follower promises not to accept lower ballots
// Returns digest of previously accepted value (if any)
type MPxPromise struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *MPxInstanceId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ballot  uint64         `protobuf:"varint,2,opt,name=ballot,proto3" json:"ballot,omitempty"` // Promised ballot number
	Ok      bool           `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`         // Promise granted
	Digest  []byte         `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`  // SHA-256 digest of previously accepted batch (if any)
	GroupId uint32         `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Members []uint32       `protobuf:"varint,6,rep,packed,name=members,proto3" json:"members,omitempty"` // Group membership list
}

func (x *MPxPromise) Reset() {
	*x = MPxPromise{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxosorderer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPxPromise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxPromise) ProtoMessage() {}

func (x *MPxPromise) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxPromise.ProtoReflect.Descriptor instead.
func (*MPxPromise) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{3}
}

func (x *MPxPromise) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxPromise) GetBallot() uint64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *MPxPromise) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MPxPromise) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *MPxPromise) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MPxPromise) GetMembers() []uint32 {
	if x != nil {
		return x.Members
	}
	return nil
}

// MPxAccept - Phase 2a: Leader proposes value after quorum of promises
// Equivalent to PBFT PREPREPARE - sends FULL BATCH to preserve client signatures
type MPxAccept struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *MPxInstanceId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ballot  uint64         `protobuf:"varint,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Batch   *Batch         `protobuf:"bytes,3,opt,name=batch,proto3" json:"batch,omitempty"` // Full Batch with original client signatures
	GroupId uint32         `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *MPxAccept) Reset() {
	*x = MPxAccept{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxosorderer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPxAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxAccept) ProtoMessage() {}

func (x *MPxAccept) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxAccept.ProtoReflect.Descriptor instead.
func (*MPxAccept) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{4}
}

func (x *MPxAccept) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxAccept) GetBallot() uint64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *MPxAccept) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *MPxAccept) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// MPxAccepted - Phase 2b: Follower accepts proposed value
// Equivalent to PBFT PREPARE - confirms acceptance to leader
type MPxAccepted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *MPxInstanceId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ballot  uint64         `protobuf:"varint,2,opt,name=ballot,proto3" json:"ballot,omitempty"`
	Ok      bool           `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"` // Value accepted
	GroupId uint32         `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *MPxAccepted) Reset() {
	*x = MPxAccepted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxosorderer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPxAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxAccepted) ProtoMessage() {}

func (x *MPxAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxAccepted.ProtoReflect.Descriptor instead.
func (*MPxAccepted) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{5}
}

func (x *MPxAccepted) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxAccepted) GetBallot() uint64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *MPxAccepted) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MPxAccepted) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// MPxCommit - Phase 3: Leader announces consensus after quorum of accepts
// Equivalent to PBFT COMMIT - sends only digest (followers already have batch)
type MPxCommit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *MPxInstanceId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Digest  []byte         `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"` // SHA-256 digest (followers use local batch)
	GroupId uint32         `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *MPxCommit) Reset() {
	*x = MPxCommit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxosorderer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPxCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxCommit) ProtoMessage() {}

func (x *MPxCommit) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxCommit.ProtoReflect.Descriptor instead.
func (*MPxCommit) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{6}
}

func (x *MPxCommit) GetId() *MPxInstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *MPxCommit) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *MPxCommit) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// MPxMsg - MultiPaxos protocol message wrapper
type MPxMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*MPxMsg_Prepare
	//	*MPxMsg_Promise
	//	*MPxMsg_Accept
	//	*MPxMsg_Accepted
	//	*MPxMsg_Commit
	Type isMPxMsg_Type `protobuf_oneof:"type"`
}

func (x *MPxMsg) Reset() {
	*x = MPxMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_multipaxosorderer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPxMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPxMsg) ProtoMessage() {}

func (x *MPxMsg) ProtoReflect() protoreflect.Message {
	mi := &file_multipaxosorderer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPxMsg.ProtoReflect.Descriptor instead.
func (*MPxMsg) Descriptor() ([]byte, []int) {
	return file_multipaxosorderer_proto_rawDescGZIP(), []int{7}
}

func (m *MPxMsg) GetType() isMPxMsg_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *MPxMsg) GetPrepare() *MPxPrepare {
	if x, ok := x.GetType().(*MPxMsg_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (x *MPxMsg) GetPromise() *MPxPromise {
	if x, ok := x.GetType().(*MPxMsg_Promise); ok {
		return x.Promise
	}
	return nil
}

func (x *MPxMsg) GetAccept() *MPxAccept {
	if x, ok := x.GetType().(*MPxMsg_Accept); ok {
		return x.Accept
	}
	return nil
}

func (x *MPxMsg) GetAccepted() *MPxAccepted {
	if x, ok := x.GetType().(*MPxMsg_Accepted); ok {
		return x.Accepted
	}
	return nil
}

func (x *MPxMsg) GetCommit() *MPxCommit {
	if x, ok := x.GetType().(*MPxMsg_Commit); ok {
		return x.Commit
	}
	return nil
}

type isMPxMsg_Type interface {
	isMPxMsg_Type()
}

type MPxMsg_Prepare struct {
	Prepare *MPxPrepare `protobuf:"bytes,1,opt,name=prepare,proto3,oneof"` // Phase 1a
}

type MPxMsg_Promise struct {
	Promise *MPxPromise `protobuf:"bytes,2,opt,name=promise,proto3,oneof"` // Phase 1b
}

type MPxMsg_Accept struct {
	Accept *MPxAccept `protobuf:"bytes,3,opt,name=accept,proto3,oneof"` // Phase 2a
}

type MPxMsg_Accepted struct {
	Accepted *MPxAccepted `protobuf:"bytes,4,opt,name=accepted,proto3,oneof"` // Phase 2b
}

type MPxMsg_Commit struct {
	Commit *MPxCommit `protobuf:"bytes,5,opt,name=commit,proto3,oneof"` // Phase 3
}

func (*MPxMsg_Prepare) isMPxMsg_Type() {}

func (*MPxMsg_Promise) isMPxMsg_Type() {}

func (*MPxMsg_Accept) isMPxMsg_Type() {}

func (*MPxMsg_Accepted) isMPxMsg_Type() {}

func (*MPxMsg_Commit) isMPxMsg_Type() {}

var File_multipaxosorderer_proto protoreflect.FileDescriptor

var file_multipaxosorderer_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x61, 0x78, 0x6f, 0x73, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x73, 0x1a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x0d, 0x4d, 0x50, 0x78, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x73, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x6c, 0x65, 0x61, 0x64, 0x22, 0x74, 0x0a, 0x08, 0x4d, 0x50, 0x78, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x4d, 0x50, 0x78,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26,
	0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x69,
	0x0a, 0x0a, 0x4d, 0x50, 0x78, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x28, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x73, 0x2e, 0x4d, 0x50, 0x78, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0xab, 0x01, 0x0a, 0x0a, 0x4d, 0x50,
	0x78, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73,
	0x2e, 0x4d, 0x50, 0x78, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x09, 0x4d, 0x50, 0x78, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x4d, 0x50,
	0x78, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x73, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x7a, 0x0a, 0x0b, 0x4d, 0x50,
	0x78, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x73, 0x2e, 0x4d, 0x50, 0x78, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x09, 0x4d, 0x50, 0x78, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x4d, 0x50, 0x78, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64,
	0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x22, 0x8c, 0x02, 0x0a, 0x06, 0x4d, 0x50, 0x78, 0x4d, 0x73, 0x67, 0x12, 0x31, 0x0a, 0x07, 0x70,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x4d, 0x50, 0x78, 0x50, 0x72, 0x65, 0x70,
	0x61, 0x72, 0x65, 0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x12, 0x31,
	0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x4d, 0x50, 0x78, 0x50,
	0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6d, 0x69, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x4d, 0x50,
	0x78, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x48, 0x00, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x12, 0x34, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e,
	0x4d, 0x50, 0x78, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x08, 0x61,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x73, 0x2e, 0x4d, 0x50, 0x78, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x48, 0x00, 0x52,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42,
	0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79,
	0x70, 0x65, 0x72, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x6d,
	0x69, 0x72, 0x62, 0x66, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_multipaxosorderer_proto_rawDescOnce sync.Once
	file_multipaxosorderer_proto_rawDescData = file_multipaxosorderer_proto_rawDesc
)

func file_multipaxosorderer_proto_rawDescGZIP() []byte {
	file_multipaxosorderer_proto_rawDescOnce.Do(func() {
		file_multipaxosorderer_proto_rawDescData = protoimpl.X.CompressGZIP(file_multipaxosorderer_proto_rawDescData)
	})
	return file_multipaxosorderer_proto_rawDescData
}

var file_multipaxosorderer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_multipaxosorderer_proto_goTypes = []any{
	(*MPxInstanceId)(nil), // 0: protobufs.MPxInstanceId
	(*MPxValue)(nil),      // 1: protobufs.MPxValue
	(*MPxPrepare)(nil),    // 2: protobufs.MPxPrepare
	(*MPxPromise)(nil),    // 3: protobufs.MPxPromise
	(*MPxAccept)(nil),     // 4: protobufs.MPxAccept
	(*MPxAccepted)(nil),   // 5: protobufs.MPxAccepted
	(*MPxCommit)(nil),     // 6: protobufs.MPxCommit
	(*MPxMsg)(nil),        // 7: protobufs.MPxMsg
	(*Batch)(nil),         // 8: protobufs.Batch
}
var file_multipaxosorderer_proto_depIdxs = []int32{
	0,  // 0: protobufs.MPxValue.id:type_name -> protobufs.MPxInstanceId
	8,  // 1: protobufs.MPxValue.batch:type_name -> protobufs.Batch
	0,  // 2: protobufs.MPxPrepare.id:type_name -> protobufs.MPxInstanceId
	0,  // 3: protobufs.MPxPromise.id:type_name -> protobufs.MPxInstanceId
	0,  // 4: protobufs.MPxAccept.id:type_name -> protobufs.MPxInstanceId
	8,  // 5: protobufs.MPxAccept.batch:type_name -> protobufs.Batch
	0,  // 6: protobufs.MPxAccepted.id:type_name -> protobufs.MPxInstanceId
	0,  // 7: protobufs.MPxCommit.id:type_name -> protobufs.MPxInstanceId
	2,  // 8: protobufs.MPxMsg.prepare:type_name -> protobufs.MPxPrepare
	3,  // 9: protobufs.MPxMsg.promise:type_name -> protobufs.MPxPromise
	4,  // 10: protobufs.MPxMsg.accept:type_name -> protobufs.MPxAccept
	5,  // 11: protobufs.MPxMsg.accepted:type_name -> protobufs.MPxAccepted
	6,  // 12: protobufs.MPxMsg.commit:type_name -> protobufs.MPxCommit
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_multipaxosorderer_proto_init() }
func file_multipaxosorderer_proto_init() {
	if File_multipaxosorderer_proto != nil {
		return
	}
	file_request_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_multipaxosorderer_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MPxInstanceId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxosorderer_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MPxValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxosorderer_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MPxPrepare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxosorderer_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MPxPromise); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxosorderer_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MPxAccept); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxosorderer_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*MPxAccepted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxosorderer_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*MPxCommit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_multipaxosorderer_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*MPxMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_multipaxosorderer_proto_msgTypes[7].OneofWrappers = []any{
		(*MPxMsg_Prepare)(nil),
		(*MPxMsg_Promise)(nil),
		(*MPxMsg_Accept)(nil),
		(*MPxMsg_Accepted)(nil),
		(*MPxMsg_Commit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_multipaxosorderer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multipaxosorderer_proto_goTypes,
		DependencyIndexes: file_multipaxosorderer_proto_depIdxs,
		MessageInfos:      file_multipaxosorderer_proto_msgTypes,
	}.Build()
	File_multipaxosorderer_proto = out.File
	file_multipaxosorderer_proto_rawDesc = nil
	file_multipaxosorderer_proto_goTypes = nil
	file_multipaxosorderer_proto_depIdxs = nil
}
