// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: request.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     *RequestID             `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	GroupId       uint32                 `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	TouchedGroups []uint32               `protobuf:"varint,6,rep,packed,name=touched_groups,json=touchedGroups,proto3" json:"touched_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRequest) GetRequestId() *RequestID {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *ClientRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *ClientRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ClientRequest) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ClientRequest) GetTouchedGroups() []uint32 {
	if x != nil {
		return x.TouchedGroups
	}
	return nil
}

type ClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientSn      int32                  `protobuf:"varint,1,opt,name=client_sn,json=clientSn,proto3" json:"client_sn,omitempty"`
	OrderSn       int32                  `protobuf:"varint,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{1}
}

func (x *ClientResponse) GetClientSn() int32 {
	if x != nil {
		return x.ClientSn
	}
	return 0
}

func (x *ClientResponse) GetOrderSn() int32 {
	if x != nil {
		return x.OrderSn
	}
	return 0
}

type RequestID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSn      int32                  `protobuf:"varint,2,opt,name=client_sn,json=clientSn,proto3" json:"client_sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestID) Reset() {
	*x = RequestID{}
	mi := &file_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestID) ProtoMessage() {}

func (x *RequestID) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestID.ProtoReflect.Descriptor instead.
func (*RequestID) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{2}
}

func (x *RequestID) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *RequestID) GetClientSn() int32 {
	if x != nil {
		return x.ClientSn
	}
	return 0
}

type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ClientRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{3}
}

func (x *Batch) GetRequests() []*ClientRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type MissingEntryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sn             int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	PayloadRequest bool                   `protobuf:"varint,2,opt,name=payload_request,json=payloadRequest,proto3" json:"payload_request,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MissingEntryRequest) Reset() {
	*x = MissingEntryRequest{}
	mi := &file_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissingEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissingEntryRequest) ProtoMessage() {}

func (x *MissingEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissingEntryRequest.ProtoReflect.Descriptor instead.
func (*MissingEntryRequest) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{4}
}

func (x *MissingEntryRequest) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *MissingEntryRequest) GetPayloadRequest() bool {
	if x != nil {
		return x.PayloadRequest
	}
	return false
}

type MissingEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            int32                  `protobuf:"varint,1,opt,name=sn,proto3" json:"sn,omitempty"`
	Batch         *Batch                 `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Aborted       bool                   `protobuf:"varint,4,opt,name=aborted,proto3" json:"aborted,omitempty"`
	Suspect       int32                  `protobuf:"varint,5,opt,name=suspect,proto3" json:"suspect,omitempty"`
	Proof         string                 `protobuf:"bytes,6,opt,name=proof,proto3" json:"proof,omitempty"` // This is a dummy proof. TODO: Implement a proper one, like a Merkle proof wrt. the checkpoint.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissingEntry) Reset() {
	*x = MissingEntry{}
	mi := &file_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissingEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissingEntry) ProtoMessage() {}

func (x *MissingEntry) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissingEntry.ProtoReflect.Descriptor instead.
func (*MissingEntry) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{5}
}

func (x *MissingEntry) GetSn() int32 {
	if x != nil {
		return x.Sn
	}
	return 0
}

func (x *MissingEntry) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *MissingEntry) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *MissingEntry) GetAborted() bool {
	if x != nil {
		return x.Aborted
	}
	return false
}

func (x *MissingEntry) GetSuspect() int32 {
	if x != nil {
		return x.Suspect
	}
	return 0
}

func (x *MissingEntry) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

type BucketSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketSubscription) Reset() {
	*x = BucketSubscription{}
	mi := &file_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketSubscription) ProtoMessage() {}

func (x *BucketSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketSubscription.ProtoReflect.Descriptor instead.
func (*BucketSubscription) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{6}
}

func (x *BucketSubscription) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type BucketAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int32                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Buckets       map[int32]*ListOfInt32 `protobuf:"bytes,2,rep,name=buckets,proto3" json:"buckets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketAssignment) Reset() {
	*x = BucketAssignment{}
	mi := &file_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketAssignment) ProtoMessage() {}

func (x *BucketAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketAssignment.ProtoReflect.Descriptor instead.
func (*BucketAssignment) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{7}
}

func (x *BucketAssignment) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *BucketAssignment) GetBuckets() map[int32]*ListOfInt32 {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type ListOfInt32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vals          []int32                `protobuf:"varint,1,rep,packed,name=vals,proto3" json:"vals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOfInt32) Reset() {
	*x = ListOfInt32{}
	mi := &file_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOfInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfInt32) ProtoMessage() {}

func (x *ListOfInt32) ProtoReflect() protoreflect.Message {
	mi := &file_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfInt32.ProtoReflect.Descriptor instead.
func (*ListOfInt32) Descriptor() ([]byte, []int) {
	return file_request_proto_rawDescGZIP(), []int{8}
}

func (x *ListOfInt32) GetVals() []int32 {
	if x != nil {
		return x.Vals
	}
	return nil
}

var File_request_proto protoreflect.FileDescriptor

const file_request_proto_rawDesc = "" +
	"\n" +
	"\rrequest.proto\x12\tprotobufs\"\x94\x01\n" +
	"\rClientRequest\x123\n" +
	"\n" +
	"request_id\x18\x01 \x01(\v2\x14.protobufs.RequestIDR\trequestId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x16\n" +
	"\x06pubkey\x18\x03 \x01(\fR\x06pubkey\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"H\n" +
	"\x0eClientResponse\x12\x1b\n" +
	"\tclient_sn\x18\x01 \x01(\x05R\bclientSn\x12\x19\n" +
	"\border_sn\x18\x02 \x01(\x05R\aorderSn\"E\n" +
	"\tRequestID\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\x12\x1b\n" +
	"\tclient_sn\x18\x02 \x01(\x05R\bclientSn\"=\n" +
	"\x05Batch\x124\n" +
	"\brequests\x18\x01 \x03(\v2\x18.protobufs.ClientRequestR\brequests\"N\n" +
	"\x13MissingEntryRequest\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12'\n" +
	"\x0fpayload_request\x18\x02 \x01(\bR\x0epayloadRequest\"\xa8\x01\n" +
	"\fMissingEntry\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\x05R\x02sn\x12&\n" +
	"\x05batch\x18\x02 \x01(\v2\x10.protobufs.BatchR\x05batch\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x18\n" +
	"\aaborted\x18\x04 \x01(\bR\aaborted\x12\x18\n" +
	"\asuspect\x18\x05 \x01(\x05R\asuspect\x12\x14\n" +
	"\x05proof\x18\x06 \x01(\tR\x05proof\"1\n" +
	"\x12BucketSubscription\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\"\xc0\x01\n" +
	"\x10BucketAssignment\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x05R\x05epoch\x12B\n" +
	"\abuckets\x18\x02 \x03(\v2(.protobufs.BucketAssignment.BucketsEntryR\abuckets\x1aR\n" +
	"\fBucketsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.protobufs.ListOfInt32R\x05value:\x028\x01\"!\n" +
	"\vListOfInt32\x12\x12\n" +
	"\x04vals\x18\x01 \x03(\x05R\x04valsB8Z6github.com/hyperledger-labs/mirbft/protobufs;protobufsb\x06proto3"

var (
	file_request_proto_rawDescOnce sync.Once
	file_request_proto_rawDescData []byte
)

func file_request_proto_rawDescGZIP() []byte {
	file_request_proto_rawDescOnce.Do(func() {
		file_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_proto_rawDesc), len(file_request_proto_rawDesc)))
	})
	return file_request_proto_rawDescData
}

var file_request_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_request_proto_goTypes = []any{
	(*ClientRequest)(nil),       // 0: protobufs.ClientRequest
	(*ClientResponse)(nil),      // 1: protobufs.ClientResponse
	(*RequestID)(nil),           // 2: protobufs.RequestID
	(*Batch)(nil),               // 3: protobufs.Batch
	(*MissingEntryRequest)(nil), // 4: protobufs.MissingEntryRequest
	(*MissingEntry)(nil),        // 5: protobufs.MissingEntry
	(*BucketSubscription)(nil),  // 6: protobufs.BucketSubscription
	(*BucketAssignment)(nil),    // 7: protobufs.BucketAssignment
	(*ListOfInt32)(nil),         // 8: protobufs.ListOfInt32
	nil,                         // 9: protobufs.BucketAssignment.BucketsEntry
}
var file_request_proto_depIdxs = []int32{
	2, // 0: protobufs.ClientRequest.request_id:type_name -> protobufs.RequestID
	0, // 1: protobufs.Batch.requests:type_name -> protobufs.ClientRequest
	3, // 2: protobufs.MissingEntry.batch:type_name -> protobufs.Batch
	9, // 3: protobufs.BucketAssignment.buckets:type_name -> protobufs.BucketAssignment.BucketsEntry
	8, // 4: protobufs.BucketAssignment.BucketsEntry.value:type_name -> protobufs.ListOfInt32
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_request_proto_init() }
func file_request_proto_init() {
	if File_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_proto_rawDesc), len(file_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_proto_goTypes,
		DependencyIndexes: file_request_proto_depIdxs,
		MessageInfos:      file_request_proto_msgTypes,
	}.Build()
	File_request_proto = out.File
	file_request_proto_goTypes = nil
	file_request_proto_depIdxs = nil
}
