// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: messenger.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Messenger_Listen_FullMethodName  = "/protobufs.Messenger/Listen"
	Messenger_Request_FullMethodName = "/protobufs.Messenger/Request"
	Messenger_Buckets_FullMethodName = "/protobufs.Messenger/Buckets"
)

// MessengerClient is the client API for Messenger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessengerClient interface {
	Listen(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProtocolMessage, BandwidthTestAck], error)
	Request(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientRequest, ClientResponse], error)
	Buckets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BucketSubscription, BucketAssignment], error)
}

type messengerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessengerClient(cc grpc.ClientConnInterface) MessengerClient {
	return &messengerClient{cc}
}

func (c *messengerClient) Listen(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProtocolMessage, BandwidthTestAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Messenger_ServiceDesc.Streams[0], Messenger_Listen_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProtocolMessage, BandwidthTestAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Messenger_ListenClient = grpc.BidiStreamingClient[ProtocolMessage, BandwidthTestAck]

func (c *messengerClient) Request(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientRequest, ClientResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Messenger_ServiceDesc.Streams[1], Messenger_Request_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientRequest, ClientResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Messenger_RequestClient = grpc.BidiStreamingClient[ClientRequest, ClientResponse]

func (c *messengerClient) Buckets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BucketSubscription, BucketAssignment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Messenger_ServiceDesc.Streams[2], Messenger_Buckets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BucketSubscription, BucketAssignment]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Messenger_BucketsClient = grpc.BidiStreamingClient[BucketSubscription, BucketAssignment]

// MessengerServer is the server API for Messenger service.
// All implementations must embed UnimplementedMessengerServer
// for forward compatibility.
type MessengerServer interface {
	Listen(grpc.BidiStreamingServer[ProtocolMessage, BandwidthTestAck]) error
	Request(grpc.BidiStreamingServer[ClientRequest, ClientResponse]) error
	Buckets(grpc.BidiStreamingServer[BucketSubscription, BucketAssignment]) error
	mustEmbedUnimplementedMessengerServer()
}

// UnimplementedMessengerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessengerServer struct{}

func (UnimplementedMessengerServer) Listen(grpc.BidiStreamingServer[ProtocolMessage, BandwidthTestAck]) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedMessengerServer) Request(grpc.BidiStreamingServer[ClientRequest, ClientResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedMessengerServer) Buckets(grpc.BidiStreamingServer[BucketSubscription, BucketAssignment]) error {
	return status.Errorf(codes.Unimplemented, "method Buckets not implemented")
}
func (UnimplementedMessengerServer) mustEmbedUnimplementedMessengerServer() {}
func (UnimplementedMessengerServer) testEmbeddedByValue()                   {}

// UnsafeMessengerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessengerServer will
// result in compilation errors.
type UnsafeMessengerServer interface {
	mustEmbedUnimplementedMessengerServer()
}

func RegisterMessengerServer(s grpc.ServiceRegistrar, srv MessengerServer) {
	// If the following call pancis, it indicates UnimplementedMessengerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Messenger_ServiceDesc, srv)
}

func _Messenger_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessengerServer).Listen(&grpc.GenericServerStream[ProtocolMessage, BandwidthTestAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Messenger_ListenServer = grpc.BidiStreamingServer[ProtocolMessage, BandwidthTestAck]

func _Messenger_Request_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessengerServer).Request(&grpc.GenericServerStream[ClientRequest, ClientResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Messenger_RequestServer = grpc.BidiStreamingServer[ClientRequest, ClientResponse]

func _Messenger_Buckets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessengerServer).Buckets(&grpc.GenericServerStream[BucketSubscription, BucketAssignment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Messenger_BucketsServer = grpc.BidiStreamingServer[BucketSubscription, BucketAssignment]

// Messenger_ServiceDesc is the grpc.ServiceDesc for Messenger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Messenger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobufs.Messenger",
	HandlerType: (*MessengerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _Messenger_Listen_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Request",
			Handler:       _Messenger_Request_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Buckets",
			Handler:       _Messenger_Buckets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "messenger.proto",
}
